### ISSUE TITLE
 Npm packages are unexpectedly downloaded from the internal registry

### ISSUE THREAD

**Issue by drik98** [dependabot/dependabot-core#10227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm@8.15.1

### Language version

node v20.12.2

### Manifest location and content before the Dependabot update

/package.json
/pnpm-lock.yaml

### dependabot.yml content

```yaml
version: 2
registries:
  npm-private:
    type: npm-registry
    url: <internal-nexus>/repository/npm-private
    token: ${{NEXUS_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - gitlabuser1
      - gitlabuser2
      - gitlabuser3
      - gitlabuser4
      - gitlabuser5
      - gitlabuser6
      - gitlabuser7
      - gitlabuser8
```

.npmrc:

```
@internal:registry=https://<internal-nexus>/repository/npm-private/
```

### Updated dependency

An internal one from the self hosted nexus.

### What you expected to see, versus what you actually saw

Given that I have _not_ set `replaces-base` on the configured registry `npm-private` to `true` and also only set the scoped registry (`@internal:registry=...`) and not `registry=...` in the `.npmrc` file I would expect that while the updated internal dependency is pulled from the self hosted nexus all other (public) packages are pulled from the official npm registry (https://registry.npmjs.org). Instead I can observe with debug log enabled that all packages are pulled from the internal nexus (see logs for more details):flag_vi:

```console
[35m[2024-07-09 05:08:09 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/@vueuse%2Fcore'
[35m[2024-07-09 05:08:10 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/@vueuse%2Fcore', status: 200
```

This results (I think) in a really slow execution of the version update (up to 10 minutes per updated dependency/creating the Merge request). This sometimes causes builds to timeout and also results in a lot of used build minutes.

## Log output

```console
[35m[2024-07-09 05:07:54 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Evaluating dependency type rule {:dependency_type=>"direct"} for @internal/package
[35m[2024-07-09 05:07:54 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Rule evaluated to 'true'
[32m[2024-07-09 05:07:54 +0000] INFO  -- [0m[dep-update: redacted/repository=>npm] Processing dependency [1m@internal/package[0m
[35m[2024-07-09 05:07:54 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/@internal%2Fpackage'
[35m[2024-07-09 05:07:55 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/@internal%2Fpackage', status: 200
[35m[2024-07-09 05:07:55 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/@internal%2Fpackage/2.0.1-990ae8fd-1364618120-dev'
[35m[2024-07-09 05:07:55 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/@internal%2Fpackage/2.0.1-990ae8fd-1364618120-dev', status: 400
...
[35m[2024-07-09 05:08:08 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Using following ignore version conditions: []
[32m[2024-07-09 05:08:08 +0000] INFO  -- [0m[dep-update: redacted/repository=>npm]   updating [1m@internal/package: 2.0.1-dadc5a59-1308155479-dev[0m => [1m2.0.1-990ae8fd-1364618120-dev[0m
...
[35m[2024-07-09 05:08:09 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/@vueuse%2Fcore'
[35m[2024-07-09 05:08:10 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/@vueuse%2Fcore', status: 200
[35m[2024-07-09 05:08:10 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/axios'
[35m[2024-07-09 05:08:11 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/axios', status: 200
[35m[2024-07-09 05:08:11 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/dayjs'
[35m[2024-07-09 05:08:11 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/dayjs', status: 200
[35m[2024-07-09 05:08:11 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/oidc-client-ts'
[35m[2024-07-09 05:08:12 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://<internal-nexus>/repository/npm-private/oidc-client-ts', status: 200
[35m[2024-07-09 05:08:12 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://<internal-nexus>/repository/npm-private/pinia'
... (and all the other dependencies)

[35m[2024-07-09 05:16:26 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser1
[35m[2024-07-09 05:16:27 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser2
[35m[2024-07-09 05:16:27 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser3
[35m[2024-07-09 05:16:27 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser4
[35m[2024-07-09 05:16:28 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser5
[35m[2024-07-09 05:16:28 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser6
[35m[2024-07-09 05:16:28 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser7
[35m[2024-07-09 05:16:28 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] Running user search for gitlabuser8
[35m[2024-07-09 05:16:29 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://registry.npmjs.org/@internal%2Fpackage/latest'
[35m[2024-07-09 05:16:30 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://registry.npmjs.org/@internal%2Fpackage/latest', status: 404
[35m[2024-07-09 05:16:30 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Performing http :get request to 'https://registry.npmjs.org/@internal%2Fpackage'
[35m[2024-07-09 05:16:30 +0000] DEBUG -- [0m[dep-update: redacted/repository=>npm] [core] Received response from 'https://registry.npmjs.org/@internal%2Fpackage', status: 404
[32m[2024-07-09 05:16:32 +0000] INFO  -- [0m[dep-update: redacted/repository=>npm]   skipping merge request [1mhttps://gitlab.com/redacted/repository/-/merge_requests/954[0m update, mr has no conflicts and rebase strategy is set to [1mauto[0m
```

**Comment by drik98** [comment]
Note: I am using dependabot on gitlab through dependabot-gitlab in the standalone version which uses dependabot-core. I created an [issue](https://gitlab.com/dependabot-gitlab/dependabot/-/issues/462) there but was pointed here as the logic regarding fetching the dependencies using the configured registries comes from the dependabot-core.

**Comment by EzraBrooks** [comment]
I'm seeing this issue as well - on GitHub, not GitLab - and it causes my Dependabot jobs to time out 100% of the time because I have a lot of dependencies and it's erroneously searching for them on GitHub Packages when it should be searching for them on npmjs.org.

**Comment by drik98** [comment]
> I'm seeing this issue as well - on GitHub, not GitLab - and it causes my Dependabot jobs to time out 100% of the time because I have a lot of dependencies and it's erroneously searching for them on GitHub Packages when it should be searching for them on npmjs.org.

„Great“ to hear that this is not a gitlab only issue. Are you able to create a github only repro?

**Comment by BPScott** [comment]
Last year this problem appeared with pnpm v8 and was resolved in #8330, but dependabot not handling pnpm v9's new lockfile format has resurfaced what appears to be the same bug. The same root issue has been reported in #9891.

It seems that with a second registry configured in dependabot.yml and no additional .npmrc, dependabot will try to a access the second registry prior to the default registry for every package, however it does not seem to configure the token correctly. For packages that exist in both the default and private registry npm will prefer the version from the private registry.

**Comment by EzraBrooks** [comment]
I do have an `.npmrc` defined, though 🤔

**Comment by BPScott** [comment]
Updated my comment as it wasn't very clear.

Having a .npmrc fixes authentication problems, however it will still try the second registry prior to the default for all packages - when it should only be trying that registry for the for packages in a given namespace

**Comment by MattIPv4** [comment]
👋 I was also running into this with pnpm -- telling Dependabot to use auth for NPM GitHub Packages, for it to then use that registry for _everything_ instead of the package scope in our .npmrc file, leading to Dependabot consistently timing out -- and @bhb603's one line fix is what got it working. Thank you so much!

I would have expected that npmjs would be used as the default given I haven't set `replaces-base` in my Dependabot config when I added the registry definition for GitHub Packages, but hey. Sounds like #7663 might be tangentially related?

**Comment by v-thavaahariharangit** [comment]
As referenced in [this comment](https://github.com/dependabot/dependabot-core/issues/10227#issuecomment-2476717784), adding the public registry configuration to your `.npmrc` file should resolve the issue.

If you have any further questions or need clarification, feel free to reach out.

I'm closing this ticket for now.

**Comment by ThW-Inform** [comment]
I have to use a different registry locally, that is not reachable for Dependabot. So, I can't use the `.npmrc` workaround. Is here any other way?

**Comment by marcus13371337** [comment]
Still experiencing this issue as of April 2026 with pnpm 9.x in a monorepo.

Our setup:
- `.npmrc` scopes our org packages: `@our-org:registry=https://npm.pkg.github.com`
- `dependabot.yml` defines the GitHub Packages registry with `replaces-base: false`

Dependabot's proxy still tries `npm.pkg.github.com` first for **all** packages. Most get a 404 and fall back to npmjs.org fine. But the subtle issue is when a package **exists on both registries with different versions** — e.g. `@types/luxon` exists on GitHub Packages with latest `2.0.9`, while npmjs.org has `3.7.1`. Since it's not a 404, the proxy uses the stale GitHub Packages response. pnpm then fails with `ERR_PNPM_NO_MATCHING_VERSION` because the lockfile requires `^3.7.1`.

This causes all Dependabot security update runs to fail consistently.

The `.npmrc` workaround (adding `registry=https://registry.npmjs.org` explicitly) fixed it for us, but `replaces-base: false` should already prevent this behavior.
