### ISSUE TITLE
Python: Support PEP 735 `[dependency-groups]` in `pyproject.toml`

### ISSUE THREAD

**Issue by vrslev** [dependabot/dependabot-core#10847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

uv recently released new version that supports now standardized `[dependency-groups]` table. See [uv 0.4.27](https://github.com/astral-sh/uv/releases/tag/0.4.27) and [PEP 735](https://peps.python.org/pep-0735/).

**Comment by dpgraham4401** [comment]
We've been experiencing issues with dependency-groups. The output we get from the dependabot logs says the following

> Dependabot can't parse your pyproject.toml
> Dependabot failed to update your dependencies because there was an error parsing the pyproject.toml found at /pyproject.toml.
> 
> Dependabot encountered the following error:
> 
> /pyproject.toml not parseable

for the following dependency-group section. 

```python
[dependency-groups]
lint = [
    "ruff==0.7.1",
    "djhtml==3.0.7"
]
test = [
    "model-bakery==1.20.0",
    "playwright==1.47.0",
    "pytest==8.3.3",
    "pytest-asyncio==0.24.0",
    "pytest-base-url==2.1.0",
    "pytest-django==4.9.0",
    "pytest-playwright==0.5.2",
    "pytest-recording==0.13.2",
    "pytest-rerunfailures==14.0",
    "pytest-cov==6.0.0",
    "vcrpy==6.0.2",
    "openapi-spec-validator==0.7.1",
    "coverage==7.6.3",
    "pytest-env==1.1.5"
]
dev = [
    "django-debug-toolbar==4.4.6",
    "django-browser-reload==1.16.0",
    "django-silk==5.2.0",
    "-e hero-tools @ {root:uri}/hero-tools",
    "setuptools-scm==8.1.0",
    "pre-commit>=4.0.1",
    { include-group = "lint" },
    { include-group = "test" },
]
```
We stop seeing the error if we either:
1. remove the `dev` group
2. combine all the groups into one.

**Comment by KyeRussell** [comment]
Additional context to hopefully nudge this one along: this is a dependency declaration standard being used _right now_ by at least one Python package / project manager (`uv` via `uv add --dev ...`). Parsing this is essentially the same as parsing `[project.optional-dependencies]`, which dependabot can already handle. It's be great to see this included!

**Comment by dpgraham4401** [comment]
It's also used by [PDM](https://pdm-project.org/en/latest/). Our team encountered error from dependabot if there were multiple groups listed under the `dependency-groups` section. 

> Dependabot can't parse your pyproject.toml
> Dependabot failed to update your dependencies because there was an error parsing the pyproject.toml found at /pyproject.toml.
> 
> Dependabot encountered the following error:
> 
> /pyproject.toml not parseable 

The logs do not include additional information about the parsing error. We were able to troubleshoot by placing all dependency-groups into one `dev` group.

**Comment by evanbernstein** [comment]
I really hope that Dependabot is updated to support dev dependencies for modern python tooling. My codebases currently use two package managers, one for dependabot and the real one, which I have to update manually when dependabot pings us to update the old one. It is gross. I'm so glad that the python community is landing on a standard, and I hope it gets implemented soon!

**Comment by AA-Turner** [comment]
The pip project has just merged support for the PEP 735 `[dependency-groups]` table (https://github.com/pypa/pip/pull/13065), which will likely be released in April.

**Comment by markhallen** [comment]
We have raised an [issue](https://github.com/emancu/toml-rb/issues/152) for the `toml-rb` gem.

If they don't have a quick fix for this we have the option to use `tomlrb` or `perfect_toml`:

```toml
# minimal.toml
[dependency-groups]
dev = [
    {"include-group" = "docs"},
    "deptry>=0.15.0",
]
docs = [
    "furo>=2024.5.6",
]
```

```ruby
irb(main):005:0> Tomlrb.load_file("minimal.toml")
=> {"dependency-groups"=>{"dev"=>[{"include-group"=>"docs"}, "deptry>=0.15.0"], "docs"=>["furo>=2024.5.6"]}}
irb(main):006:0> PerfectTOML.load_file("minimal.toml")
=> {"dependency-groups"=>{"dev"=>[{"include-group"=>"docs"}, "deptry>=0.15.0"], "docs"=>["furo>=2024.5.6"]}}
```

**Comment by markhallen** [comment]
This is closed for `uv`, but I need to test the handling for other python package managers before closing.

**Comment by evanbernstein** [comment]
@markhallen Thanks for doing this. If I'm reading this correctly, if I switch from `rye` to `uv` then Dependabot will work correctly for all packages? If so, I've found a new project for today.

**Comment by rslinckx** [comment]
I can't find the code that looks for dependency-groups in dependabot, according to the comment above it seems to have been fixed, but what was fixed is only the parser understanding the toml, not the actual extraction of dependency-groups ?

**Comment by abdulapopoola** [comment]
@rslinckx , here is the PR: https://github.com/dependabot/dependabot-core/pull/11796#issuecomment-2726503472

**Comment by rslinckx** [comment]
As you can see here: https://github.com/dependabot/dependabot-core/blob/main/uv/helpers/lib/parser.py#L58 the only sections that are parsed are `dependencies` and `optional-dependencies`. I'm not even sure why the ruby gem toml has any relevance since it's python code reading and parsing the pyproject.toml anyway? (the call site is around here: https://github.com/dependabot/dependabot-core/blob/main/uv/lib/dependabot/uv/file_parser/pyproject_files_parser.rb#L93 )

**Comment by MusicalNinjaDad** [comment]
The issue fixed by #11796 was that the updater, which uses rb-toml, errored out as described in [this comment](https://github.com/dependabot/dependabot-core/issues/10478#issuecomment-2692737602)

**Comment by edgarrmondragon** [comment]
There still seem to be some TOML issues, strangely only affecting some dependencies.

<details><summary>Details</summary>
<p>

```
updater | 2025/03/19 15:32:39 ERROR <job_983290999> Error processing setuptools (NoMethodError)
2025/03/19 15:32:39 ERROR <job_983290999> undefined method `keys' for an instance of String
updater | 2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:32:in `sort_pairs'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:77:in `block (2 levels) in dump_table_array_pairs'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:75:in `each'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:75:in `block in dump_table_array_pairs'
updater | 2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:71:in `each'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:71:in `dump_table_array_pairs'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:52:in `dump_pairs'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:24:in `visit'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:66:in `block in dump_nested_pairs'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:63:in `each'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:63:in `dump_nested_pairs'
updater | 2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:51:in `dump_pairs'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:24:in `visit'
updater | 2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb/dumper.rb:12:in `initialize'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb.rb:97:in `new'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/toml-rb-4.0.0/lib/toml-rb.rb:97:in `dump'
2025/03/19 15:32:39 ERROR <job_983290999> /home/dependabot/uv/lib/dependabot/uv/file_updater/pyproject_preparer.rb:37:in `freeze_top_level_dependencies_except'
```

</p>
</details> 

apparently happening in https://github.com/dependabot/dependabot-core/blob/0d360049df196added830612e22c8620d17c4c00/uv/lib/dependabot/uv/file_updater/pyproject_preparer.rb#L37

For reference:

- https://github.com/meltano/meltano/actions/runs/13950441068/job/39048269473
- https://github.com/meltano/meltano/blob/main/pyproject.toml

**Comment by rslinckx** [comment]
Unfortunately the uv ecosystem still doesn't look for the legacy `[tool.uv].dev-dependencies` or the new `[dependency-groups].dev` keys, so the UV updater cannot possibly update dev dependencies nor present them as dev dependencies according to dependabot filtering/grouping rules

**Comment by Paul-B98** [comment]
any update?

**Comment by SMoraisAnsys** [comment]
> any update?

Following a [previous comment](https://github.com/dependabot/dependabot-core/issues/10847#issuecomment-2727599153) a PR has been opened to support dependency groups in the python ecosystem (not for `uv`).

**Comment by phillipuniverse** [comment]
FYI the uv solution is a bit unique from other Python package managers because uv is its own "ecosystem". But it was originally copied from the python ecosystem so all the files line up.

Therefore I opened #12720. @SMoraisAnsys this just takes the excellent work you did and copies it over to the uv ecosystem. I'm cool with putting that in 1 PR (if maintainers would prefer that for whatever reason), I just want to see this merged!

**Comment by phillipuniverse** [comment]
@SMoraisAnsys teamwork makes the dream work! 🤝

**Comment by phillipuniverse** [comment]
Confirmed working on the UV side with the new release this morning

pyproject.toml

<img width="347" height="243" alt="Image" src="https://github.com/user-attachments/assets/d6656eb9-5730-4d13-9005-a48c03e0e23f" />

Things like Ruff/mypy are included in the Dependabot PR:

<img width="543" height="582" alt="Image" src="https://github.com/user-attachments/assets/f875d89e-f051-487f-affb-d8fa3ff6467f" />

**Comment by amureki** [comment]
> Confirmed working on the UV side with the new release this morning

@phillipuniverse Great news!

Thanks for all the collaboration and contributions here!
May I go a little bit offtopic and ask how your dependabot group setup looks like?
I had it looking like this on one of the projects and it was not able to pick up any updates at all:

```yml
version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-python-dependencies:
        update-types:
          - "minor"
          - "patch"
      major-python-dependencies:
        update-types:
          - "major"
```

**Comment by JamieMagee** [comment]
PEP 735 support is in. The parser detects and processes `[dependency-groups]` sections in `pyproject.toml`.

**Comment by jorenham** [comment]
awesome; thanks!
