### ISSUE TITLE
NPM version detection broken

### ISSUE THREAD

**Issue by chbiel** [dependabot/dependabot-core#11234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

10.8.2

### Language version

20.16.0

### Manifest location and content before the Dependabot update

package.json excerpt
´´´
"engines": {
    "npm": ">=10",
    "node": ">=20"
  },
´´´

.npmrc
```
engine-strict=true
```

### What you expected to see, versus what you actually saw

Problem: Somewhen between 05.12.2024 and 9.12.2024 our dependabot setup for NPM broke for all projects that included above mentioned config (`npm >= 10` + `engine-strict=true`) and so did not update any NPM dependencies anymore.
The timespan is based on the last successful and then following first failed run, no run in between.

It's very hard to get all information together but I will try in the following:

Partial log of a successful run on 05.12.2024:
```
updater | 2024/12/04 05:18:39 INFO <job_927237043> Guessed version info "npm" : "10"
updater | 2024/12/04 05:18:39 INFO <job_9272[37](SOME_URL)043> Installing "npm@10"
  proxy | 2024/12/04 05:18:39 [008] GET https://registry.npmjs.org:443/npm
  proxy | 2024/12/04 05:18:39 [008] 200 [https://registry.npmjs.org:443/npm](SOME_URL) [010] GET https://registry.npmjs.org:443/npm/-/npm-10.9.1.tgz
  proxy | 2024/12/04 05:18:39 [010] 200 [https://registry.npmjs.org:443/npm](https://registry.npmjs.org/npm)/-/npm-10.9.1.tgz
updater | 2024/12/04 05:18:[40](SOME_URL) INFO <job_927237043> Fetching version for package manager: npm
updater | 2024/12/04 05:18:40 INFO <job_927237043> Running package manager command: corepack npm -v
updater | 2024/12/04 05:18:[41](SOME_URL) INFO <job_927237043> Command executed successfully: corepack npm -v
2024/12/04 05:18:41 INFO <job_927237043> Version for npm: 10.9.1
updater | 2024/12/04 05:18:41 INFO <job_9272370[43](SOME_URL)> Installed version of npm: 10.9.1
  proxy | 2024/12/04 05:18:41 [012] POST /update_jobs/927237043/record_ecosystem_versions
  proxy | 2024/12/04 05:18:41 [012] 204 /update_jobs/927237043/record_ecosystem_versions
updater | 2024/12/04 05:18:41 INFO <job_927237043> Base commit SHA: ...[44](SOME_URL)
updater | 2024/12/04 05:18:41 INFO <job_927237043> Finished job processing
updater | 2024/12/04 05:18:44 INFO <job_927237043> Starting job processing
updater | 2024/12/04 05:18:44 INFO <job_927237043> Detected package manager: npm
updater | 2024/12/04 05:18:44 INFO <job_927237043> Resolving package manager for: npm
updater | 2024/12/04 05:18:44 INFO <job_927237043> Fetching version for package manager: npm
updater | 2024/12/04 05:18:44 INFO <job_927237043> Running package manager command: corepack npm -v
updater | 2024/12/04 05:18:44 INFO <job_927237043> Command executed successfully: corepack npm -v
2024/12/04 05:18:44 INFO <job_927237043> Version for npm: 10.9.1
updater | 2024/12/04 05:18:44 INFO <job_927237043> Installed version for npm: 10.9.1
```

Partial log of a failing run on 09.12.2024:
```
updater | 2024/12/09 18:17:25 INFO <job_929896445> Guessed version info "npm" : "10"
updater | 2024/12/09 18:17:25 INFO <job_929896445> Installing "npm@10"
  proxy | 2024/12/09 18:17:25 [008] GET [https://registry.npmjs.org:443/npm](https://registry.npmjs.org/npm)
  proxy | 2024/12/09 18:17:25 [008] 200 https://registry.npmjs.org:443/npm
  proxy | 2024/12/09 18:17:25 [010] GET https://registry.npmjs.org:443/npm/-/npm-10.9.2.tgz
  proxy | 2024/12/09 18:17:25 [010] 200 https://registry.npmjs.org:443/npm/-/npm-10.9.2.tgz
updater | 2024/12/09 18:17:26 INFO <job_929896445> npm@10 successfully installed.
updater | 2024/12/09 18:17:26 INFO <job_929896445> Fetching version for package manager: npm
updater | 2024/12/09 18:17:27 INFO <job_929896445> Installed version of npm: 9.6.5
  proxy | 2024/12/09 18:17:27 [012] POST /update_jobs/929896445/record_ecosystem_versions
  proxy | 2024/12/09 18:17:27 [012] 204 /update_jobs/929896445/record_ecosystem_versions
updater | 2024/12/09 18:17:27 INFO <job_929896445> Base commit SHA: 8755fd18fe4c768b[39](SOME_URL)965e541a5fd991ce4322fa
updater | 2024/12/09 18:17:27 INFO <job_929896445> Finished job processing
updater | 2024/12/09 18:17:30 INFO <job_929896445> Starting job processing
updater | 2024/12/09 18:17:30 INFO <job_929896445> Detected package manager: npm
updater | 2024/12/09 18:17:30 INFO <job_929896[44](SOME_URL)5> Resolving package manager for: npm
updater | 2024/12/09 18:17:30 INFO <job_9298964[45](SOME_URL)> Fetching version for package manager: npm
updater | 2024/12/09 18:17:30 INFO <job_929896445> Installed version of npm: 9.6.5
updater | 2024/12/09 18:17:30 INFO <job_929896445> Installed version for npm: 9.6.5
```

And now all dependabot jobs run with `npm 9.6.5` instead of `10` like before.

What can be noticed is, that in the successful run, `corepack` is used. In the later failing run, `corepack` calls are missing.

From this comment https://github.com/dependabot/dependabot-core/pull/10985#discussion_r1852977132 it sounds like, that actually version `10` of NPM should be used, but as said, it's not.

The only way to work around this right now is to remove `engine-strict=true` from the `.npmrc`, what we would like to prevent.
And in the end dependabot does not run the NPM version we would like to see.

As the whole issue (and for me connecting all the dots) is relatively hard, please tell me, if / what more information you need to have a look at the issue.
As the projects are private, I cannot provide direct likes or so.

Related:
https://github.com/dependabot/dependabot-core/issues/10982
https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories (says only npm 9 is supported)
https://github.com/dependabot/dependabot-core/discussions/11159 (announces that NPM 11 is supported)
https://github.com/dependabot/dependabot-core/pull/10985 (sounds related but only a feeling...)

**Comment by natehouk** [comment]
+1

**Comment by LukaPrebil** [comment]
Not sure if this is the same issue, but we've noticed dependabot fails to resolve the npm version and errors assuming the version is empty, even though it previously detects 9.6.5

```
2025/01/22 12:55:45 INFO <job_952072306> Resolving package manager for: npm
updater | 2025/01/22 12:55:45 INFO <job_952072306> Fetching version for package manager: npm
updater | 2025/01/22 12:55:45 INFO <job_952072306> Started process PID: 4088 with command: {} corepack npm -v {}
updater | 2025/01/22 12:55:46 INFO <job_952072306> Process PID: 4088 completed with status: pid 4088 exit 0
updater | 2025/01/22 12:55:46 INFO <job_952072306> Total execution time: 0.41 seconds
updater | 2025/01/22 12:55:46 INFO <job_952072306> Installed version of npm: 9.6.5
updater | 2025/01/22 12:55:46 INFO <job_952072306> Installed version for npm: 9.6.5
updater | 2025/01/22 12:55:46 INFO <job_952072306> Processing engine constraints for npm
updater | 2025/01/22 12:55:46 INFO <job_952072306> No version requirement found for npm
updater | 2025/01/22 12:55:46 INFO <job_952072306> Running node command: node -v
updater | 2025/01/22 12:55:46 INFO <job_952072306> Started process PID: 4100 with command: {} node -v {}
updater | 2025/01/22 12:55:46 INFO <job_952072306> Process PID: 4100 completed with status: pid 4100 exit 0
updater | 2025/01/22 12:55:46 INFO <job_952072306> Total execution time: 0.01 seconds
2025/01/22 12:55:46 INFO <job_952072306> Command executed successfully: node -v
2025/01/22 12:55:46 INFO <job_952072306> Processing engine constraints for node
updater | 2025/01/22 12:55:46 ERROR <job_952072306> Dependabot detected the following npm requirement for your project: ''.

Currently, the following npm versions are supported in Dependabot: v7.*, v8.*, v9.*, v10.*.
```

**Comment by timbru31** [comment]
We are having the same issue where Dependabot suddenly says our npm version is not supported. This started happening yesterday.

```
updater | 2025/01/21 13:17:23 INFO <job_951301726> Resolving package manager for: npm
2025/01/21 13:17:23 INFO <job_951301726> Installed version for npm: 9.6.5
2025/01/21 13:17:23 INFO <job_951301726> Processing engine constraints for npm
2025/01/21 13:17:23 INFO <job_951301726> No version requirement found for npm
  proxy | 2025/01/21 13:17:23 [008] POST /update_jobs/951301726/record_ecosystem_versions
  proxy | 2025/01/21 13:17:23 [008] 204 /update_jobs/951301726/record_ecosystem_versions
updater | 2025/01/21 13:17:23 INFO <job_951301726> Base commit SHA: a4055e8baf28f22cab786520ef46b3c8bdf140e2
updater | 2025/01/21 13:17:23 INFO <job_951301726> Finished job processing
updater | 2025/01/21 13:17:25 INFO <job_951301726> Starting job processing
updater | 2025/01/21 13:17:25 INFO <job_951301726> Default package manager used: npm
updater | 2025/01/21 13:17:25 INFO <job_951301726> Resolving package manager for: npm
updater | 2025/01/21 13:17:25 INFO <job_951301726> Fetching version for package manager: npm
updater | 2025/01/21 13:17:25 INFO <job_951301726> Started process PID: 1345 with command: {} corepack npm -v {}
updater | 2025/01/21 13:17:26 INFO <job_951301726> Process PID: 1345 completed with status: pid 1345 exit 0
updater | 2025/01/21 13:17:26 INFO <job_951301726> Total execution time: 0.44 seconds
2025/01/21 13:17:26 INFO <job_951301726> Installed version of npm: 9.6.5
2025/01/21 13:17:26 INFO <job_951301726> Installed version for npm: 9.6.5
2025/01/21 13:17:26 INFO <job_951301726> Processing engine constraints for npm
2025/01/21 13:17:26 INFO <job_951301726> No version requirement found for npm
updater | 2025/01/21 13:17:26 INFO <job_951301726> Running node command: node -v
updater | 2025/01/21 13:17:26 INFO <job_951301726> Started process PID: 1357 with command: {} node -v {}
updater | 2025/01/21 13:17:26 INFO <job_951301726> Process PID: 1357 completed with status: pid 1357 exit 0
updater | 2025/01/21 13:17:26 INFO <job_951301726> Total execution time: 0.01 seconds
2025/01/21 13:17:26 INFO <job_951301726> Command executed successfully: node -v
2025/01/21 13:17:26 INFO <job_951301726> Processing engine constraints for node
updater | 2025/01/21 13:17:26 ERROR <job_951301726> Dependabot detected the following npm requirement for your project: ''.

Currently, the following npm versions are supported in Dependabot: v7.*, v8.*, v9.*, v10.*.
  proxy | 2025/01/21 13:17:26 [011] POST /update_jobs/951301726/record_update_job_error
  proxy | 2025/01/21 13:17:26 [011] 204 /update_jobs/951301726/record_update_job_error
  proxy | 2025/01/21 13:17:26 [013] PATCH /update_jobs/951301726/mark_as_processed
  proxy | 2025/01/21 13:17:26 [013] 204 /update_jobs/951301726/mark_as_processed
updater | 2025/01/21 13:17:26 INFO <job_951301726> Finished job processing
updater | 2025/01/21 13:17:26 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------+
|           Errors           |
+----------------------------+
| tool_version_not_supported |
+----------------------------+
Failure running container 878f9c271bb7015a5c307228f2c817fe629c629c0d6c2399305b69636a3d1b9c
Cleaned up container 878f9c271bb7015a5c307228f2c817fe629c629c0d6c2399305b69636a3d1b9c
```

**Comment by lorenz-maurer** [comment]
We ran into the same error in multiple repositories. It started happening from 21.01.2025 on.
It only seems to affect projects which specify multiple `repositories` within the `dependabot.yml`

`2025/01/23 06:54:57 INFO <job_952467230> Resolving package manager for: npm
updater | 2025/01/23 06:54:57 INFO <job_952467230> Fetching version for package manager: npm
updater | 2025/01/23 06:54:57 INFO <job_952467230> Started process PID: 2212 with command: {} corepack npm -v {}
updater | 2025/01/23 06:54:57 INFO <job_952467230> Process PID: 2212 completed with status: pid 2212 exit 0
updater | 2025/01/23 06:54:57 INFO <job_952467230> Total execution time: 0.45 seconds
updater | 2025/01/23 06:54:57 INFO <job_952467230> Installed version of npm: 9.6.5
updater | 2025/01/23 06:54:57 INFO <job_952467230> Installed version for npm: 9.6.5
2025/01/23 06:54:57 INFO <job_952467230> Processing engine constraints for npm
2025/01/23 06:54:57 INFO <job_952467230> No version requirement found for npm
updater | 2025/01/23 06:54:57 INFO <job_952467230> Running node command: node -v
updater | 2025/01/23 06:54:57 INFO <job_952467230> Started process PID: 2224 with command: {} node -v {}
updater | 2025/01/23 06:54:57 INFO <job_952467230> Process PID: 2224 completed with status: pid 2224 exit 0
updater | 2025/01/23 06:54:57 INFO <job_952467230> Total execution time: 0.01 seconds
2025/01/23 06:54:57 INFO <job_952467230> Command executed successfully: node -v
2025/01/23 06:54:57 INFO <job_952467230> Processing engine constraints for node
updater | 2025/01/23 06:54:57 ERROR <job_952467230> Dependabot detected the following npm requirement for your project: ''.

Currently, the following npm versions are supported in Dependabot: v7.*, v8.*, v9.*, v10.*.
  proxy | 2025/01/23 06:54:57 [026] POST /update_jobs/952467230/record_update_job_error
  proxy | 2025/01/23 06:54:57 [026] 204 /update_jobs/952467230/record_update_job_error
  proxy | 2025/01/23 06:54:57 [028] PATCH /update_jobs/952467230/mark_as_processed
  proxy | 2025/01/23 06:54:57 [028] 204 /update_jobs/952467230/mark_as_processed
updater | 2025/01/23 06:54:57 INFO <job_952467230> Finished job processing
updater | 2025/01/23 06:54:57 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------+
|           Errors           |
+----------------------------+
| tool_version_not_supported |
+----------------------------+
Failure running container 05010eb658da0d4f6958a7451a64a52988b66e93f4126bd2ca3f1e45bc8d0e10
Cleaned up container 05010eb658da0d4f6958a7451a64a52988b66e93f4126bd2ca3f1e45bc8d0e10`

**Comment by ntkme** [comment]
It seems dependabot detect npm version requirement from lock file, instead of from `packages.json`'s `"engines"` field:

https://github.com/dependabot/dependabot-core/issues/11373

**Comment by ntkme** [comment]
https://github.com/dependabot/dependabot-core/pull/11392

**Comment by Ayush272002** [comment]
The same issue arises when dependabot is used with nodejs monorepos, 

this is my dependabot.yml
```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 30
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: auto

  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
      - 'backend'

  - package-ecosystem: 'npm'
    directory: '/packages/db'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
      - 'db'
```


it only updates for the root `package.json` and then it fails to update for the rest.

**Comment by ArjunRajpal123** [comment]
I am also having the same issue

**Comment by kbukum1** [comment]
Hi everyone,  

The PR addressing the npm version detection issue has been shipped. Could you test your repositories and let us know if the problem is resolved? If not, please share details or logs here for further investigation.  

- https://github.com/dependabot/dependabot-core/pull/11392

**Comment by timbru31** [comment]
Restarted a job, same issue for our jobs

```
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1107 completed with status: pid 1107 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.93 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1150 with command: {} git -C /home/dependabot/dependabot-updater/repo ls-files --stage {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1150 completed with status: pid 1150 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1163 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/git.store' {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1163 completed with status: pid 1163 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1170 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1170 completed with status: pid 1170 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1176 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1176 completed with status: pid 1176 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1182 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1182 completed with status: pid 1182 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1188 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1188 completed with status: pid 1188 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1194 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1194 completed with status: pid 1194 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1200 with command: {} git lfs pull --include .yarn,./yarn/cache {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1200 completed with status: pid 1200 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.04 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1233 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/git.store' {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1233 completed with status: pid 1233 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1240 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1240 completed with status: pid 1240 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1246 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1246 completed with status: pid 1246 exit 0
2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1252 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1252 completed with status: pid 1252 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.02 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1258 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1258 completed with status: pid 1258 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1264 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1264 completed with status: pid 1264 exit 0
2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1270 with command: {} git rev-parse HEAD {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1270 completed with status: pid 1270 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.02 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1283 with command: {} git config --global credential.helper '!/home/dependabot/common/lib/dependabot/../../bin/git-credential-store-immutable --file /home/dependabot/dependabot-updater/git.store' {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1283 completed with status: pid 1283 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1290 with command: {} git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1290 completed with status: pid 1290 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1296 with command: {} git config --global --add url.https://github.com/.insteadOf ssh://git@github.com: {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1296 completed with status: pid 1296 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1302 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com: {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1302 completed with status: pid 1302 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1308 with command: {} git config --global --add url.https://github.com/.insteadOf git@github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1308 completed with status: pid 1308 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1314 with command: {} git config --global --add url.https://github.com/.insteadOf git://github.com/ {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1314 completed with status: pid 1314 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1320 with command: {} git rev-parse HEAD {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1320 completed with status: pid 1320 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.01 seconds
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Fetching version for package manager: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Started process PID: 1326 with command: {} corepack npm -v {}
updater | 2025/01/28 16:18:43 INFO <job_955015767> Process PID: 1326 completed with status: pid 1326 exit 0
updater | 2025/01/28 16:18:43 INFO <job_955015767> Total execution time: 0.48 seconds
2025/01/28 16:18:43 INFO <job_955015767> Installed version of npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
updater | 2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
updater | 2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:43 INFO <job_955015767> Default package manager used: npm
2025/01/28 16:18:43 INFO <job_955015767> Resolving package manager for: npm
2025/01/28 16:18:43 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:43 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:43 INFO <job_955015767> No version requirement found for npm
  proxy | 2025/01/28 16:18:44 [008] POST /update_jobs/955015767/record_ecosystem_versions
  proxy | 2025/01/28 16:18:44 [008] 204 /update_jobs/955015767/record_ecosystem_versions
updater | 2025/01/28 16:18:44 INFO <job_955015767> Base commit SHA: eb6e90c5a29c313794477771713b9c0e9aa23600
updater | 2025/01/28 16:18:44 INFO <job_955015767> Finished job processing
updater | 2025/01/28 16:18:45 INFO <job_955015767> Starting job processing
updater | 2025/01/28 16:18:45 INFO <job_955015767> Default package manager used: npm
updater | 2025/01/28 16:18:45 INFO <job_955015767> Resolving package manager for: npm
updater | 2025/01/28 16:18:45 INFO <job_955015767> Fetching version for package manager: npm
updater | 2025/01/28 16:18:45 INFO <job_955015767> Started process PID: 1344 with command: {} corepack npm -v {}
updater | 2025/01/28 16:18:46 INFO <job_955015767> Process PID: 1344 completed with status: pid 1344 exit 0
updater | 2025/01/28 16:18:46 INFO <job_955015767> Total execution time: 0.46 seconds
2025/01/28 16:18:46 INFO <job_955015767> Installed version of npm: 9.6.5
2025/01/28 16:18:46 INFO <job_955015767> Installed version for npm: 9.6.5
2025/01/28 16:18:46 INFO <job_955015767> Processing engine constraints for npm
2025/01/28 16:18:46 INFO <job_955015767> No version requirement found for npm
updater | 2025/01/28 16:18:46 INFO <job_955015767> Running node command: node -v
updater | 2025/01/28 16:18:46 INFO <job_955015767> Started process PID: 1356 with command: {} node -v {}
updater | 2025/01/28 16:18:46 INFO <job_955015767> Process PID: 1356 completed with status: pid 1356 exit 0
updater | 2025/01/28 16:18:46 INFO <job_955015767> Total execution time: 0.01 seconds
2025/01/28 16:18:46 INFO <job_955015767> Command executed successfully: node -v
2025/01/28 16:18:46 INFO <job_955015767> Processing engine constraints for node
updater | 2025/01/28 16:18:46 ERROR <job_955015767> Dependabot detected the following npm requirement for your project: ''.
Currently, the following npm versions are supported in Dependabot: v7.*, v8.*, v9.*, v10.*.
  proxy | 2025/01/28 16:18:46 [011] POST /update_jobs/955015767/record_update_job_error
  proxy | 2025/01/28 16:18:46 [011] 204 /update_jobs/955015767/record_update_job_error
  proxy | 2025/01/28 16:18:46 [013] PATCH /update_jobs/955015767/mark_as_processed
  proxy | 2025/01/28 16:18:46 [013] 204 /update_jobs/955015767/mark_as_processed
updater | 2025/01/28 16:18:46 INFO <job_955015767> Finished job processing
updater | 2025/01/28 16:18:46 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------+
|           Errors           |
+----------------------------+
| tool_version_not_supported |
+----------------------------+
Failure running container 3bf1fc039db093d1b2ac2749089e87da88b791f950e8b272d5e2687f5278251e
Cleaned up container 3bf1fc039db093d1b2ac2749089e87da88b791f950e8b272d5e2687f5278251e
  proxy | 2025/01/28 16:18:46 0/6 calls cached (0%)
  proxy | 2025/01/28 16:18:46 Posting metrics to remote API endpoint
Error: Dependabot encountered an error performing the update

Error: The updater encountered one or more errors.
```

**Comment by bcomnes** [comment]
Packages that define an engines range like this, without a `package-lock.json`:

```json
"engines": {
    "node": ">=19.0.0",
    "npm": ">=9.0.0"
  },
```

Stopped working last week, and started working again after the fix that just went out.

However, repos that don't define a npm engine range and also don't have a lockfile still don't work, and stopped working last week.  Essentially, these repos don't define an npm engines range, or just define their node version range now have broken dependabot integrations. 

It's really important that these repos continue to get updates. Failing to find a specific range shouldn't result in an error. 

Can you make it so that repos that don't define an engine range or have a lockfile work by default, by selecting some default working version of npm? 

```
2025/01/28 19:00:01 INFO <job_955079126> Resolving package manager for: npm
2025/01/28 19:00:01 INFO <job_955079126> Installed version for npm: 9.6.5
2025/01/28 19:00:01 INFO <job_955079126> Processing engine constraints for npm
2025/01/28 19:00:01 INFO <job_955079126> No version requirement found for npm
  proxy | 2025/01/28 19:00:01 [008] POST /update_jobs/955079126/record_ecosystem_versions
  proxy | 2025/01/28 19:00:02 [008] 204 /update_jobs/955079126/record_ecosystem_versions
updater | 2025/01/28 19:00:02 INFO <job_955079126> Base commit SHA: 009f54aca3e7965b71397141ff8102d9df5cf3e6
updater | 2025/01/28 19:00:02 INFO <job_955079126> Finished job processing
updater | 2025/01/28 19:00:03 INFO <job_955079126> Starting job processing
updater | 2025/01/28 19:00:03 INFO <job_955079126> Default package manager used: npm
updater | 2025/01/28 19:00:03 INFO <job_955079126> Resolving package manager for: npm
updater | 2025/01/28 19:00:03 INFO <job_955079126> Fetching version for package manager: npm
updater | 2025/01/28 19:00:03 INFO <job_955079126> Started process PID: 1379 with command: {} corepack npm -v {}
updater | 2025/01/28 19:00:04 INFO <job_955079126> Process PID: 1379 completed with status: pid 1379 exit 0
updater | 2025/01/28 19:00:04 INFO <job_955079126> Total execution time: 0.27 seconds
updater | 2025/01/28 19:00:04 INFO <job_955079126> Installed version of npm: 9.6.5
2025/01/28 19:00:04 INFO <job_955079126> Installed version for npm: 9.6.5
updater | 2025/01/28 19:00:04 INFO <job_955079126> Processing engine constraints for npm
2025/01/28 19:00:04 INFO <job_955079126> No version requirement found for npm
updater | 2025/01/28 19:00:04 INFO <job_955079126> Running node command: node -v
updater | 2025/01/28 19:00:04 INFO <job_955079126> Started process PID: 1391 with command: {} node -v {}
updater | 2025/01/28 19:00:04 INFO <job_955079126> Process PID: 1391 completed with status: pid 1391 exit 0
2025/01/28 19:00:04 INFO <job_955079126> Total execution time: 0.01 seconds
updater | 2025/01/28 19:00:04 INFO <job_955079126> Command executed successfully: node -v
updater | 2025/01/28 19:00:04 INFO <job_955079126> Processing engine constraints for node
updater | 2025/01/28 19:00:04 ERROR <job_955079126> Dependabot detected the following npm requirement for your project: ''.

Currently, the following npm versions are supported in Dependabot: v7.*, v8.*, v9.*, v10.*.
  proxy | 2025/01/28 19:00:04 [011] POST /update_jobs/955079126/record_update_job_error
  proxy | 2025/01/28 19:00:04 [011] 204 /update_jobs/955079126/record_update_job_error
  proxy | 2025/01/28 19:00:04 [013] PATCH /update_jobs/955079126/mark_as_processed
  proxy | 2025/01/28 19:00:04 [013] 204 /update_jobs/955079126/mark_as_processed
updater | 2025/01/28 19:00:04 INFO <job_955079126> Finished job processing
updater | [202](https://github.com/hifiwi-fi/breadcrum.net/actions/runs/13017584967/job/36310465636#step:3:204)5/01/28 19:00:04 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+----------------------------+
|           Errors           |
+----------------------------+
| tool_version_not_supported |
+----------------------------+
Failure running container 6e3e13fc34cdf97df83d78f6756723f955998567fbe7f91050bfb8566dda1317
Cleaned up container 6e3e13fc34cdf97df83d78f6756723f955998567fbe7f91050bfb8566dda1317
  proxy | 2025/01/28 19:00:04 0/6 calls cached (0%)
2025/01/28 19:00:04 Posting metrics to remote API endpoint
```

**Comment by kbukum1** [comment]
Hi everyone,

I believe the following PR will resolve the unsupported error issue. It still requires testing on a repository similar to yours, but I'll proceed with deployment after receiving feedback and approval.

- https://github.com/dependabot/dependabot-core/pull/11430

Feel free to review it.

Note: You can ignore pipeline errors for now which are not related to the PR.

**Comment by kbukum1** [comment]
Hi everyone,

The fix for the unsupported error has been shipped. Please confirm if the issue is now resolved.  

- https://github.com/dependabot/dependabot-core/pull/11430

CC: @LukaPrebil, @timbru31, @lorenz-maurer, @bcomnes

**Comment by kbukum1** [comment]
The issue has been fixed:

- https://github.com/dependabot/dependabot-core/pull/11430

**Comment by chbiel** [comment]
@kbukum1 unfortunately the issue persists for us:

```
...
updater | 2025/01/30 07:51:45 INFO <job_955947936> Detected package manager: npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Resolving package manager for: npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Returned (engines) info "npm" : ""
updater | 2025/01/30 07:51:45 INFO <job_955947936> Guessed version info "npm" : "10"
updater | 2025/01/30 07:51:45 INFO <job_955947936> Fetching version for package manager: npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Started process PID: 1326 with command: {} corepack npm -v {}
updater | 2025/01/30 07:51:45 INFO <job_955947936> Process PID: 1326 completed with status: pid 1326 exit 0
updater | 2025/01/30 07:51:45 INFO <job_955947936> Total execution time: 0.48 seconds
updater | 2025/01/30 07:51:45 INFO <job_955947936> Installed version of npm: 9.6.5
2025/01/30 07:51:45 INFO <job_955947936> Installed version for npm: 9.6.5
updater | 2025/01/30 07:51:45 INFO <job_955947936> Processing engine constraints for npm
updater | 2025/01/30 07:51:45 WARN <job_955947936> Unrecognized constraint format for npm: >= 10
2025/01/30 07:51:45 ERROR <job_955947936> Error processing constraints for npm: undefined method `join' for nil
2025/01/30 07:51:45 INFO <job_955947936> No version requirement found for npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Detected package manager: npm
2025/01/30 07:51:45 INFO <job_955947936> Resolving package manager for: npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Returned (engines) info "npm" : ""
updater | 2025/01/30 07:51:45 INFO <job_955947936> Guessed version info "npm" : "10"
updater | 2025/01/30 07:51:45 INFO <job_955947936> Installed version for npm: 9.6.5
2025/01/30 07:51:45 INFO <job_955947936> Processing engine constraints for npm
2025/01/30 07:51:45 WARN <job_955947936> Unrecognized constraint format for npm: >= 10
2025/01/30 07:51:45 ERROR <job_955947936> Error processing constraints for npm: undefined method `join' for nil
2025/01/30 07:51:45 INFO <job_955947936> No version requirement found for npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Returned (engines) info "npm" : ""
updater | 2025/01/30 07:51:45 INFO <job_955947936> Guessed version info "npm" : "10"
updater | 2025/01/30 07:51:45 INFO <job_955947936> Detected package manager: npm
2025/01/30 07:51:45 INFO <job_955947936> Resolving package manager for: npm
updater | 2025/01/30 07:51:45 INFO <job_955947936> Returned (engines) info "npm" : ""
updater | 2025/01/30 07:51:45 INFO <job_955947936> Guessed version info "npm" : "10"
updater | 2025/01/30 07:51:45 INFO <job_955947936> Installed version for npm: 9.6.5
2025/01/30 07:51:45 INFO <job_955947936> Processing engine constraints for npm
2025/01/30 07:51:45 WARN <job_955947936> Unrecognized constraint format for npm: >= 10
...
```

So we can still not ensure that npm `10` is used, what happened to be the default last year, when `corepack` was used for managing npm versions (maybe I misunderstand something here, but that is what I understand from the logs in the initial report).

Although the log states `Guessed version info "npm" : "10"`, what is a new log line that was not appearing before, it still has problems parsing the version constraint:
```
2025/01/30 07:51:45 WARN <job_955947936> Unrecognized constraint format for npm: >= 10
2025/01/30 07:51:45 ERROR <job_955947936> Error processing constraints for npm: undefined method `join' for nil
```

Basically it got worse now. The initial logs at least tried to install `npm10` (but then used `npm9` instead):

```
updater | 2024/12/09 18:17:25 INFO <job_929896445> Guessed version info "npm" : "10"
updater | 2024/12/09 18:17:25 INFO <job_929896445> Installing "npm@10"
  proxy | 2024/12/09 18:17:25 [008] GET [https://registry.npmjs.org:443/npm](https://registry.npmjs.org/npm)
  proxy | 2024/12/09 18:17:25 [008] 200 https://registry.npmjs.org:443/npm
  proxy | 2024/12/09 18:17:25 [010] GET https://registry.npmjs.org:443/npm/-/npm-10.9.2.tgz
  proxy | 2024/12/09 18:17:25 [010] 200 https://registry.npmjs.org:443/npm/-/npm-10.9.2.tgz
updater | 2024/12/09 18:17:26 INFO <job_929896445> npm@10 successfully installed.
updater | 2024/12/09 18:17:26 INFO <job_929896445> Fetching version for package manager: npm
updater | 2024/12/09 18:17:27 INFO <job_929896445> Installed version of npm: 9.6.5
```

now I cannot find any logs anymore, that try to install `npm10`.

Also referering to a comment in the PR https://github.com/dependabot/dependabot-core/pull/11430#issuecomment-2622615072 it looks like we are running into a state that should not happen.
We have `lockfileVersion: 3` so we should end up with `npm10`.

I also think that some comments from other users relate to other issues, especially the one that confirmed your PR to be working.

Can you please have a look again?

**Comment by timbru31** [comment]
For us the job is working again and Dependabot opened a bunch of PRs again.

**Comment by kbukum1** [comment]
**Subject:** Follow-up on Fix – Issue Resolution  

Hi @timbru31, @bcomnes,  

Did the fix mentioned in the comment below resolve the issue, or are you still experiencing problems?  

- https://github.com/dependabot/dependabot-core/pull/11430#issuecomment-2622618210

I plan to close this issue if everything is working fine. However, if you're still facing any problems, I'd be happy to investigate further.  

Looking forward to your feedback!

**Comment by kbukum1** [comment]
> >= 10

@chbiel , 

Can you change the range from ">= 10" to ">=10"?

**Comment by chbiel** [comment]
@kbukum1 upated to `>=10.0.0` to be sure.

At least the version detection errors are gone with that and it also looks like `npm10` gets downloaded, but the installed/used npm version stays at `npm9`:

```
updater | 2025/02/03 07:40:37 INFO <job_957785895> Detected package manager: npm
updater | 2025/02/03 07:40:37 INFO <job_957785895> Resolving package manager for: npm
updater | 2025/02/03 07:40:37 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | 2025/02/03 07:40:37 INFO <job_957785895> Installed version for npm: 9.6.5
updater | 2025/02/03 07:40:37 INFO <job_957785895> Processing engine constraints for npm
updater | 2025/02/03 07:40:37 INFO <job_957785895> Parsed constraints for npm: >=10.0.0
updater | 2025/02/03 07:40:37 INFO <job_957785895> Version requirement for npm: >= 10.0.0
updater | 2025/02/03 07:40:37 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | 2025/02/03 07:40:37 INFO <job_957785895> Installing "npm@10"
updater | 2025/02/03 07:40:37 INFO <job_957785895> Started process PID: 1450 with command: {} corepack install npm@10 --global --cache-only {}
  proxy | 2025/02/03 07:40:37 [008] GET [https://registry.npmjs.org:443/npm](https://registry.npmjs.org/npm)
  proxy | 2025/02/03 07:40:37 [008] 200 [https://registry.npmjs.org:443/npm](https://registry.npmjs.org/npm)
  proxy | 2025/02/03 07:40:38 [010] GET [https://registry.npmjs.org:443/npm/-/npm-10.9.2.tgz](https://registry.npmjs.org/npm/-/npm-10.9.2.tgz)
  proxy | 2025/02/03 07:40:38 [010] 200 [https://registry.npmjs.org:443/npm/-/npm-10.9.2.tgz](https://registry.npmjs.org/npm/-/npm-10.9.2.tgz)
  proxy | 2025/02/03 07:40:39 [012] GET [https://registry.npmjs.org:443/npm/10.9.2](https://registry.npmjs.org/npm/10.9.2)
  proxy | 2025/02/03 07:40:40 [012] 200 [https://registry.npmjs.org:443/npm/10.9.2](https://registry.npmjs.org/npm/10.9.2)
updater | 2025/02/03 07:40:40 INFO <job_957785895> Process PID: 1450 completed with status: pid 1450 exit 0
2025/02/03 07:40:40 INFO <job_957785895> Total execution time: 3.14 seconds
updater | 2025/02/03 07:40:40 INFO <job_957785895> Detected package manager: npm
2025/02/03 07:40:40 INFO <job_957785895> Resolving package manager for: npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | 2025/02/03 07:40:40 INFO <job_957785895> Installed version for npm: 9.6.5
2025/02/03 07:40:40 INFO <job_957785895> Processing engine constraints for npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Parsed constraints for npm: >=10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Version requirement for npm: >= 10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Detected package manager: npm
2025/02/03 07:40:40 INFO <job_957785895> Resolving package manager for: npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | [202](https://github.com/JH-JDS/fms-frontend-components/actions/runs/13108607893/job/36567548592#step:3:204)5/02/03 07:40:40 INFO <job_957785895> Installed version for npm: 9.6.5
updater | 2025/02/03 07:40:40 INFO <job_957785895> Processing engine constraints for npm
2025/02/03 07:40:40 INFO <job_957785895> Parsed constraints for npm: >=10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Version requirement for npm: >= 10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Detected package manager: npm
2025/02/03 07:40:40 INFO <job_957785895> Resolving package manager for: npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | 2025/02/03 07:40:40 INFO <job_957785895> Installed version for npm: 9.6.5
2025/02/03 07:40:40 INFO <job_957785895> Processing engine constraints for npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Parsed constraints for npm: >=10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Version requirement for npm: >= 10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Detected package manager: npm
2025/02/03 07:40:40 INFO <job_957785895> Resolving package manager for: npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | 2025/02/03 07:40:40 INFO <job_957785895> Installed version for npm: 9.6.5
2025/02/03 07:40:40 INFO <job_957785895> Processing engine constraints for npm
2025/02/03 07:40:40 INFO <job_957785895> Parsed constraints for npm: >=10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Version requirement for npm: >= 10.0.0
updater | 2025/02/03 07:40:40 INFO <job_957785895> Detected package manager: npm
2025/02/03 07:40:40 INFO <job_957785895> Resolving package manager for: npm
updater | 2025/02/03 07:40:40 INFO <job_957785895> Returned (engines) info "npm" : "10"
updater | 2025/02/03 07:40:40 INFO <job_957785895> Installed version for npm: 9.6.5
```

**Comment by kbukum1** [comment]
@chbiel,  

Thanks for the update. We're currently using detected versions for manifest file updates. However, due to an existing issue related to Corepack, we're temporarily running install/update processes using a fixed version, "9.6.5". We're actively working on resolving this issue and plan to enable the use of the installed (detected) package manager version for install/update processes soon.

**Comment by kbukum1** [comment]
@chbiel,  

Thanks for the update. We're currently using detected versions for manifest file updates. However, due to an existing issue related to Corepack, we're temporarily running install/update processes using a fixed version, "9.6.5". We're actively working on resolving this issue and plan to enable the use of the installed (detected) package manager version for install/update processes soon.

**Comment by chbiel** [comment]
@kbukum1 thanks for the information. Is there an open issue that I can subscribe to?

**Comment by jansepke** [comment]
@kbukum1 is there any update, can this issue be reopenend?

**Comment by W0nderMuffin** [comment]
hey there,
we can reproduce this error

```
github/dependabot-action@ghes-3.15
```

package.json:
```
  "engines": {
    "node": "22.14.0",
    "pnpm": "^10.4.1"
  },
```
and .npmrc

```
engine-strict=true
registry=https://registry.npmjs.org
```

logs:

```
updater | 2025/08/19 08:21:27 INFO <job_1005603> Latest version is 4.4.1
updater | 2025/08/19 08:21:27 INFO <job_1005603> Adding dependencies as handled: (@stylistic/eslint-plugin).
updater | 2025/08/19 08:21:30 INFO <job_1005603> Requirements to unlock own
updater | 2025/08/19 08:21:30 INFO <job_1005603> Requirements update strategy bump_versions
updater | 2025/08/19 08:21:30 INFO <job_1005603> Updating @stylistic/eslint-plugin from 4.2.0 to 4.4.1
  proxy | 2025/08/19 08:21:32 [331] POST [https://***:443/_dependabot/update_jobs/1005603/record_update_job_error](https://***/_dependabot/update_jobs/1005603/record_update_job_error)
  proxy | 2025/08/19 08:21:32 [331] 204 [https://***:443/_dependabot/update_jobs/1005603/record_update_job_error](https://***/_dependabot/update_jobs/1005603/record_update_job_error)
updater | 2025/08/19 08:21:32 INFO <job_1005603> Handled error whilst updating @stylistic/eslint-plugin: tool_version_not_supported {"tool-name": "Node", "detected-version": "22.14.0", "supported-versions": "v20.19.3"}
```

**Comment by v-kbukum1** [comment]
> hey there, we can reproduce this error
> 
> ```
> github/dependabot-action@ghes-3.15
> ```
> 
> package.json:
> 
> ```
>   "engines": {
>     "node": "22.14.0",
>     "pnpm": "^10.4.1"
>   },
> ```
> 
> and .npmrc
> 
> ```
> engine-strict=true
> registry=https://registry.npmjs.org
> ```
> 
> logs:
> 
> ```
> updater | 2025/08/19 08:21:27 INFO <job_1005603> Latest version is 4.4.1
> updater | 2025/08/19 08:21:27 INFO <job_1005603> Adding dependencies as handled: (@stylistic/eslint-plugin).
> updater | 2025/08/19 08:21:30 INFO <job_1005603> Requirements to unlock own
> updater | 2025/08/19 08:21:30 INFO <job_1005603> Requirements update strategy bump_versions
> updater | 2025/08/19 08:21:30 INFO <job_1005603> Updating @stylistic/eslint-plugin from 4.2.0 to 4.4.1
>   proxy | 2025/08/19 08:21:32 [331] POST [https://***:443/_dependabot/update_jobs/1005603/record_update_job_error](https://***/_dependabot/update_jobs/1005603/record_update_job_error)
>   proxy | 2025/08/19 08:21:32 [331] 204 [https://***:443/_dependabot/update_jobs/1005603/record_update_job_error](https://***/_dependabot/update_jobs/1005603/record_update_job_error)
> updater | 2025/08/19 08:21:32 INFO <job_1005603> Handled error whilst updating @stylistic/eslint-plugin: tool_version_not_supported {"tool-name": "Node", "detected-version": "22.14.0", "supported-versions": "v20.19.3"}
> ```


Hi @W0nderMuffin ,

If we don't have another related issue, is it possible if we can create an issue for that. I think that's related to supported current node and npm versions and needs to be checked but it is not related to this issue anymore.

**Comment by W0nderMuffin** [comment]
> > hey there, we can reproduce this error
> > ```
> > github/dependabot-action@ghes-3.15
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > package.json:
> > ```
> >   "engines": {
> >     "node": "22.14.0",
> >     "pnpm": "^10.4.1"
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and .npmrc
> > ```
> > engine-strict=true
> > registry=https://registry.npmjs.org
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > logs:
> > ```
> > updater | 2025/08/19 08:21:27 INFO <job_1005603> Latest version is 4.4.1
> > updater | 2025/08/19 08:21:27 INFO <job_1005603> Adding dependencies as handled: (@stylistic/eslint-plugin).
> > updater | 2025/08/19 08:21:30 INFO <job_1005603> Requirements to unlock own
> > updater | 2025/08/19 08:21:30 INFO <job_1005603> Requirements update strategy bump_versions
> > updater | 2025/08/19 08:21:30 INFO <job_1005603> Updating @stylistic/eslint-plugin from 4.2.0 to 4.4.1
> >   proxy | 2025/08/19 08:21:32 [331] POST [https://***:443/_dependabot/update_jobs/1005603/record_update_job_error](https://***/_dependabot/update_jobs/1005603/record_update_job_error)
> >   proxy | 2025/08/19 08:21:32 [331] 204 [https://***:443/_dependabot/update_jobs/1005603/record_update_job_error](https://***/_dependabot/update_jobs/1005603/record_update_job_error)
> > updater | 2025/08/19 08:21:32 INFO <job_1005603> Handled error whilst updating @stylistic/eslint-plugin: tool_version_not_supported {"tool-name": "Node", "detected-version": "22.14.0", "supported-versions": "v20.19.3"}
> > ```
> 
> Hi [@W0nderMuffin](https://github.com/W0nderMuffin) ,
> 
> If we don't have another related issue, is it possible if we can create an issue for that. I think that's related to supported current node and npm versions and needs to be checked but it is not related to this issue anymore.

hey,
thx for reply. I already created a new ticket: https://github.com/dependabot/dependabot-core/issues/12976
