### ISSUE TITLE
error running tests in development shell due to directories mapped as volumes

### ISSUE THREAD

**Issue by dmitris** [dependabot/dependabot-core#11553]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

go_modules

### What you expected to see, versus what you actually saw

I'm following instructions on https://github.com/dependabot/dependabot-core/tree/main/go_modules: in a fresh git checkout  commit `0f4c9422426c37534ceb5f300252eef81db9a5a3`, I do:
```bash
$ bin/docker-dev-shell go_modules -r
[...]

=> running docker development shell
=> running docker development shell
docker: Error response from daemon: error while creating mount source path '/Users/dmitris/gh/dependabot/dependabot-core/javascript/helpers': chown /Users/dmitris/gh/dependabot/dependabot-core/javascript/helpers: permission denied.
```

I also tried to run `git clean -fdx` and re-run the commands above, but with the same result / error.
After removing `javascript/helpers`, I had the same error with `omnibus/Gemfile`, therefore removed that one as well.

**Comment by dmitris** [comment]
I tried with the `v0.295.0`  (from Jan 30 2025) and it works fine, no error:
```bash
[dependabot-core-dev] ~/go_modules $ rspec spec

Randomized with seed 50613
...*........................................................................................................
```
Something causing this must have been introduced recently, in the last two weeks.

**Comment by kbukum1** [comment]
@dmitris , 

Thank you for letting us know. The problem is solved. Can you check it now?

```
=> running docker development shell
[dependabot-core-dev] ~ $ cd go_modules/
[dependabot-core-dev] ~/go_modules $ rspec .

Randomized with seed 50395
......................................................................................................................
```

**Comment by dmitris** [comment]
> Thank you for letting us know. The problem is solved. Can you check it now?

I'm still getting a failure 
```bash
=> running docker development shell
docker: Error response from daemon: error while creating mount source path '/Users/dmitris/gh/dependabot/dependabot-core/omnibus/Gemfile': chown /Users/dmitris/gh/dependabot/dependabot-core/omnibus/Gemfile: permission denied.
```
so I think https://github.com/dependabot/dependabot-core/pull/11563 is still needed (at least for me / some users 😄 ) - it removes this line in `dev/docker-dev/shell:.
```sh
-v "$(pwd)/omnibus/Gemfile:$CODE_DIR/omnibus/Gemfile" \
```

I keep updating the PR branch - maybe you could review the PR? I would appreciate it. Thanks.
