### ISSUE TITLE
[bun] bun package-manager does not update bun.lock

### ISSUE THREAD

**Issue by ghoullier** [dependabot/dependabot-core#11602]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

bun

### Package manager version

1.2.2

### Manifest location and content before the Dependabot update

./package.json

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies"]
    commit-message:
      prefix: "chore"
      include: "scope"

### Updated dependency

[@types/bun](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/bun)

### What you expected to see, versus what you actually saw

package.json and bun.lock must be updated in the dependabot pr

### Native package manager behavior

bun.lock is updated (see  [ci log](https://github.com/ghoullier/bun-typescript-template/actions/runs/13331956541/job/37238022350?pr=186))

### Images of the diff or a link to the PR, issue, or logs

https://github.com/ghoullier/bun-typescript-template/pull/186

**Comment by Alex-ley-scrub** [comment]
@ghoullier you might want to look at this comment here - I had the same issue and "fixed" it (at least for my use case) with a `dependabot.yml` change: https://github.com/dependabot/dependabot-core/issues/6528#issuecomment-2718062536

**Comment by ghoullier** [comment]
@Alex-ley-scrub Thanks it fix the issue on my repo (see https://github.com/ghoullier/bun-typescript-template/pull/200)

@markhallen if it's the exepected behavior maybe thhis should be mentioned in the [doc](https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories#bun)

**Comment by Alex-ley-scrub** [comment]
@ghoullier, nice - I would think it is supposed to update the `bun.lock` without the need for the `enable-beta-ecosystems: true` option but let's see what @markhallen says

**Comment by agatatocz** [comment]
Hi, I'm having the same issue - dependabot does not update `bun.lock` but in my case `enable-beta-ecosystems: true` didn't help. My project is a monorepo set up using bun workspaces, so the `bun.lock` is located on the root level and `package.json` files are placed inside of apps folders. Does dependabot support bun workspaces?

**Comment by marcellodesales** [comment]
So so important feature that must be working at this point

**Comment by sedghi** [comment]
same as @agatatocz , bun.lock in a monorepo does not work

**Comment by markhallen** [comment]
This should be resolved by a PR merged yesterday: https://github.com/dependabot/dependabot-core/pull/12021

Let me know here if it resolved your issue. You can also notify here if it didn't and we can reopen the issue. Thanks for your continued support.

**Comment by agatatocz** [comment]
Hi @markhallen, thank you for working on this. I can see that dependabot just created a PR in my repo and the issue still persists - it only updated `package.json` but not `bun.lock`. Should I do something specific in my dependabot config to make it work with bun workspaces?

**Comment by skylarmb** [comment]
Still seeing this issue, with every combination of adding/removing `enable-beta-ecosystems` and using either `npm` or `bun` as the `package-ecosystem`. No combination causes dependabot to properly update the lockfile.

**Comment by tmr232** [comment]
In my repo it seems that for regular dependency updates it updates the lock file, but for security ones it does not.

**Comment by filipfalcon** [comment]
Is there any update for this issue? In my repository, which utilizes [Bun workspaces](https://bun.sh/docs/install/workspaces), the pull request is only created with updated `package.json`, the `bun.lock` file remains untouched.

**Comment by agatatocz** [comment]
Hi @markhallen, it seems that more people have the same problem. Could you please reopen the issue?

**Comment by alandotcom** [comment]
Definitely still an issue.

**Comment by dmitritsoy** [comment]
The same issue

**Comment by sweepies** [comment]
Can we get this moving?

**Comment by karyanayandi** [comment]
any update?
