### ISSUE TITLE
Dependabot has stopped providing the changelog of updated dependencies

### ISSUE THREAD

**Issue by patrickomeara** [dependabot/dependabot-core#12531]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

composer

### Package manager version

2.8.9

### Language version

8.4.8

### Manifest location and content before the Dependabot update

composer.json

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Australia/Melbourne"
    ignore:
      - dependency-name: "laravel/cashier-paddle"
        versions: [">=2"]
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "07:00"
      timezone: "Australia/Melbourne"
    groups:
      actions:
        patterns:
          - "*"
```

### What you expected to see, versus what you actually saw

The last two times (weekly) dependabot runs, but does not provide any info about the packages it has updated.

![Image](https://github.com/user-attachments/assets/28204bc3-54b6-4633-a7cc-69f7be2f1f4e)

**Comment by reduckted** [comment]
I just encountered this on https://github.com/reduckted/GitWebLinks/pull/374

Package ecosystem was npm.

**Comment by matijs** [comment]
Maybe a duplicate of https://github.com/dependabot/dependabot-core/issues/12253?

This started happenening for one of my repos for the `npm` ecosystem. What that repo has in common with @patrickomeara's and @reduckted's repos and the one in the linked issue, is the presence of a `groups` and `ignore` block:

```yaml
groups:
  non-major-dependencies:
    applies-to: "version-updates"
    update-types:
      - "patch"
      - "minor"
ignore:
  - dependency-name: "react"
    update-types:
      - "version-update:semver-major"
  - dependency-name: "react-dom"
    update-types:
      - "version-update:semver-major"
```

Another repo that has no issues has a `groups` block but _no_ `ignore` block:

```yaml
groups:
  non-major-dependencies:
    applies-to: "version-updates"
    update-types:
      - "patch"
      - "minor"
```

**Update**
After merging the PR without changelogs I triggered Dependbot by hand and it created a tiny PR with just 2 updated dependencies that both had changelogs once again. 🤷

**Update 2025-07-14**
A PR with 11 updates did not have any changelogs. 😔

**Comment by 3raser95** [comment]
I have a private repo that has `groups` but no `ignore` and I'm experiencing this same issue there so I don't think the `ignore` is causing the issue.

**Comment by nicou** [comment]
Also experiencing this issue in our repos while using `groups` but no `ignore`.

**Comment by reduckted** [comment]
> I just encountered this on [reduckted/GitWebLinks#374](https://github.com/reduckted/GitWebLinks/pull/374)

In case it helps track down what's causing it, the pull request from seven days earlier did show the changelog.
https://github.com/reduckted/GitWebLinks/pull/373

**Comment by patrickomeara** [comment]
Yeah, this has only been an issue for me for the last two weeks. Nothing has changed on the dependabot settings side of things. I have other repos that use dependabot that still show the changelog

**Comment by 3raser95** [comment]
Just actually had dependabot create three different PRs today and none of them showed the changelog. After merging two of them the third one got recreated and the new PR suddenly had the correct changelogs appear. Really weird behaviour.

**Comment by ethanmdavidson** [comment]
Also happening for me, and I have very simple configs:

```yaml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

**Comment by Stanzilla** [comment]
Happened to several repos of mine, all using pnpm

**Comment by alexei** [comment]
Can confirm release notes no longer show up for "pip" either

**Comment by ashkulz** [comment]
Happens for us as well, for the `ruby` / `bundler` ecosystem.

**Comment by patrickomeara** [comment]
I think it might be a character length issue, the more dependencies that are updated, the more likely to lose the changelog.

**Comment by ashkulz** [comment]
> I think it might be a character length issue, the more dependencies that are updated, the more likely to lose the changelog.

It's happening for all PRs, and I suspect a regression in the latest release which is deployed to GitHub. PRs for last week were okay, this week weren't (_we generate them weekly on Sunday_).

**Comment by patrickomeara** [comment]
We also have a weekly schedule. Today the changelog was present and only 3 dependencies were updated, the two iterations before were 10+ dependencies and didn't have changelog.

**Comment by Stanzilla** [comment]
Still busted this week

**Comment by pjaws** [comment]
Just started seeing this for new PRs in one of my repos today. Nothing has changed in our config.

**Comment by lguida-nasdaq** [comment]
I'm seeing the same for `gomod` updates,.

**Comment by pauleustice** [comment]
Hi everyone - we've seen a similar thing. It's due to rate limiting in our case; please check the logs in the workflow run under `Dependabot Updates` in your Actions tab; search for "rate limit" and you'll probably find that it appears multiple times. It implies Dependabot can't reach the API for getting details about each package / release.

Not sure if this is something that started since Dependabot infrastructure moved over onto GitHub Actions, possibly?

**Comment by patrickomeara** [comment]
Nice find @pauleustice, I have them in my logs as well. This would explain the changelog coming through when there are less dependencies updated.

```
updater | 2025/07/13 21:50:28 ERROR <job_1051870431> Error while generating PR message: GET https://api.github.com/repos/laravel/slack-notification-channel/commits?sha=v3.6.0: 403 - API rate limit exceeded for 20.41.8.186. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
updater | 2025/07/13 21:50:28 ERROR <job_1051870431> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/octokit-7.2.0/lib/octokit/response/raise_error.rb:14:in 'Octokit::Response::RaiseError#on_complete'
```

**Comment by ReenigneArcher** [comment]
This is happening for me too, but not all PRs.

not working: https://github.com/LizardByte/Sunshine/pull/4089
working: https://github.com/LizardByte/build-deps/pull/467

**Comment by FreekVR** [comment]
I am seeing a similar problem:

```
updater | 2025/07/21 01:51:51 ERROR <job_1056831908> Error while generating commit message: GET https://api.github.com/repos/xxx/releases?per_page=100: 403 - API rate limit exceeded for 57.154.172.162. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
```

I couldn't find any clear instruction on how to get dependabot to run with authenticated API requests but that may be the solution?

**Comment by Clashsoft** [comment]
Why doesn't it at least show the new and old versions? Why would it need to make an API request for that? It could just provide a link to the releases page or changelog file instead of omitting the whole useful part of the description.

**Comment by MattIPv4** [comment]
X-posting https://github.com/dependabot/dependabot-core/issues/12253#issuecomment-3113967434:

> I've spoken to GitHub support about this, their advice is...
> 
> > At this time our best option to get your workflows unblocked it to leverage a PAT as we've been discussing. The method for you to use is the `git` [method listed in our docs](https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#git).

**Comment by jakecoffman** [comment]
This should be fixed now, see #12253 for details.

**Comment by yeikel** [comment]
Note that a similar issue came back https://github.com/dependabot/dependabot-core/issues/13569
