### ISSUE TITLE
Groups not being respected

### ISSUE THREAD

**Issue by gregauger** [dependabot/dependabot-core#13154]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

npm 10

### Manifest location and content before the Dependabot update

{
  "name": "dependabot-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build --turbopack",
    "start": "next start",
    "lint": "eslint"
  },
  "dependencies": {
    "@sentry/nextjs": "10.12.0",
    "@tanstack/react-query": "5.89.0",
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "next": "15.5.3"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "@tailwindcss/postcss": "^4",
    "tailwindcss": "^4",
    "eslint": "^9",
    "eslint-config-next": "15.5.3",
    "knip": "5.63.1",
    "lint-staged": "16.1.6",
    "@eslint/eslintrc": "^3"
  }
}

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifest
    schedule:
      interval: 'daily' # How often to check for updates
      time: '07:00'
      timezone: 'Europe/London'
    open-pull-requests-limit: 15
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - 'patch'
      minor-updates:
        applies-to: version-updates
        update-types:
          - 'minor'

### What you expected to see, versus what you actually saw

Expected to see: minor updates grouped together in a single PR (i.e. lint-staged, @sentry/nextjs, eslint, knip, @tanstack/react-query)

Actually seen: separate PRs for each of these minor version updates.
<img width="759" height="542" alt="Image" src="https://github.com/user-attachments/assets/4ef9f173-c9c1-4dd3-b968-8263e38ac68a" />

### Images of the diff or a link to the PR, issue, or logs

[logs_46066055265.zip](https://github.com/user-attachments/files/22488736/logs_46066055265.zip)
https://github.com/gregauger/dependabot-test/actions/runs/17939010735/job/51010882994

```
updater | 2025/09/23 07:36:33 WARN <job_1106768455> Please check your configuration as there are groups where no dependencies match:
- minor-updates

This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
```

**Comment by Kovah** [comment]
I can second this. It's not just happening for npm, but also Composer (PHP) and Docker.

Example config:

```yaml
- package-ecosystem: "composer"
  directory: "/"
  target-branch: "2.x"
  schedule:
    interval: "weekly"
  groups:
    composer-major:
      update-types:
        - "major"
    composer-minor:
      update-types:
        - "minor"
        - "patch"
```

Yet Dependabot opened a dozen PRs for every single dependency. The issue first came up yesterday but not last week, so the bug likely exists for a few days?

**Comment by huehnerlady** [comment]
We have the same problem. Our gradle projects are fine

our dependabot file:
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular-major: # group angular dependencies and the store dependencies together
        patterns:
          - "@angular*"
          - "@ngxs*"
          - "ngx-float-ui"
        update-types:
          - major
      angular-minor: # group angular dependencies together for minor updates
        patterns:
          - "@angular*"
        update-types:
          - minor
          - patch
      ngxs-minor: # group ngxs dependencies together for minor updates
        patterns:
          - "@ngxs*"
        update-types:
          - minor
          - patch
      nx: # group nx- dependencies together
        patterns:
          - "@nx/nx-*"
        update-types:
          - major
      eslint: # group eslint dependencies together
        patterns:
          - "@typescript-eslint/*"
        update-types:
          - major
      all: # group all minor/patch updates
        patterns:
          - "*"
        exclude-patterns:
          - "@fontsource/inter" # separate PR
          - "typescript" # separate PR
        update-types:
          - minor
          - patch
```

our PRs:
<img width="796" height="191" alt="Image" src="https://github.com/user-attachments/assets/cfb02188-ef65-4386-beb6-f7e58a39e650" />

Our error message:
```
updater | 2025/09/23 11:19:47 WARN <job_1106894900> Please check your configuration as there are groups where no dependencies match:
- angular-minor
- ngxs-minor

This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
```

**Comment by VorpalBlade** [comment]
I'm seeing the same thing for cargo dependencies (Rust). I have a group for minor version bumps. This is being ignored starting this week. So it isn't just JS.

However, github action updates seem to group fine.

**Comment by deshack** [comment]
I'm seeing the same for some gradle dependencies too

**Comment by tim3z** [comment]
This seems to be caused by the `update-types` and independent of the language. Merging groups with different `update-types` solved it/configurations where there was just one group per language didn't have this problem.

**Comment by huehnerlady** [comment]
> This seems to be caused by the `update-types` and independent of the language. Merging groups with different `update-types` solved it/configurations where there was just one group per language didn't have this problem.

Can you give an example how to sole the issue?
Do you mean you can only have a group per update type? What if you do not specify the types?

**Comment by tim3z** [comment]
> Can you give an example how to sole the issue?

Not really, at least none that is equivalent in behavior. But if you go from

```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      npm-major-dependencies:
        patterns:
          - '*'
        update-types:
          - major
      npm-minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
```

to


```yaml
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      npm-dependencies:
        patterns:
          - '*'
```

you get everything in one group. Which to me is better than all the individual PRs. 

I don't know if this is specifically about the `update-types` or generally about multiple groups in one entry. But since every example posted here included `update-types` my bet would be on that one.

**Comment by VorpalBlade** [comment]
While that is a useful trick I want major updates in separate PRs and minor grouped as one big PR. So not really a solution.

**Comment by robaiken** [comment]
Hi everyone! I've been working on improving the pattern matching for groups but unfortunately messed up non-pattern groups in the process. The initial issue should be solved now. 

I'm currently investigating how patterns and update-types aren't playing nice together and working on a fix for any remaining cases.

**Comment by huehnerlady** [comment]
> Hi everyone! I've been working on improving the pattern matching for groups but unfortunately messed up non-pattern groups in the process. The initial issue should be solved now.
> 
> I'm currently investigating how patterns and update-types aren't playing nice together and working on a fix for any remaining cases.

We do have the same problem still unfortunately

**Comment by creydr** [comment]
> We do have the same problem still unfortunately

same here (with Golang dependencies)

**Comment by huehnerlady** [comment]
@robaiken could you please reopen the issue as the problem still exists?

**Comment by robaiken** [comment]
@creydr @huehnerlady could you provide more details on what's not working for you? I closed the issue because there's a fix for @gregauger's specific problem. You're likely experiencing an issue with similar symptoms but a different underlying cause. 

To help me investigate further, could you either create an example repo demonstrating the issue (if it's private), share a link to the failing workflow (if it's public), or send me the logs from a failed workflow along with your `dependabot.yml`?

Also, if there are any PRs that were opened before this fix was released, the best thing to do is close those problematic PRs and wait for the next scheduled run.

**Comment by robsterlini** [comment]
@robaiken I can try and get a repo demo together tomorrow unless someone else beats me to it, but I was getting the same error listed in the description:

```
updater | 2025/09/29 10:57:44 WARN <job_1111338746> Please check your configuration as there are groups where no dependencies match:
- mui-major
- patch

This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
```

This listed groups that definitely had valid dependencies:

```yml
      mui-major:
        patterns:
          - "@mui/*"
        update-types:
          - "major"
```

but interestingly those two groups _only_ have wildcard patterns. `mui-major` has `@mui/*` and `patch` is just `*` as a catch all.

I added a fixed value to each of the `patterns` arrays (in my case `husky` for `patch` and `@mui/material` for `mui-major`) that wouldn't have matched any other groups, and it has started generating grouped PRs again:

```yml
      mui-major:
        patterns:
          # Temporary value to force the group to be created
          # @see https://github.com/dependabot/dependabot-core/issues/13154
          - "@mui/material"
          - "@mui/*"
        update-types:
          - "major"
```

Not sure if this helps diagnose the issue any further, but it seems to be working for us as a temporary workaround.

**Comment by robsterlini** [comment]
Update: sadly this seems to have been premature, it is still inconsistently grouping the wildcards. Will try and get a repo together tomorrow (at the earliest) to help.

**Comment by robaiken** [comment]
@robsterlini It sounds like `update-types` and `patterns` aren't working well together. I'm looking into this issue today. A real-world example would be great when you have a chance to put one together, thanks!

**Comment by creydr** [comment]
Thanks a lot @robaiken for checking on this!
We are seeing this for example on this [PR list](https://github.com/openshift-knative/eventing-kafka-broker/issues?q=is%3Apr%20is%3Aopen%20author%3Aapp%2Fdependabot). I'd have expected for example the following minor version updates being grouped together:
* openshift-knative/eventing-kafka-broker#2035
* openshift-knative/eventing-kafka-broker#2034
* openshift-knative/eventing-kafka-broker#2033


And this is our dependabot config: [.github/dependabot.yml](https://github.com/openshift-knative/eventing-kafka-broker/blob/main/.github/dependabot.yml)

---

Also in another repo (Golang & node modules) by this [PR list](https://github.com/openshift-knative/backstage-plugins/issues?q=is%3Apr%20is%3Aopen%20author%3Aapp%2Fdependabot) ([.github/dependabot.yml](https://github.com/openshift-knative/backstage-plugins/blob/main/.github/dependabot.yml))

I hope this helps

**Comment by robaiken** [comment]
@robsterlini did you have a chance to make an example repo?

**Comment by huehnerlady** [comment]
@robaiken not sure if this helps, but I created a sample project [here](https://github.com/huehnerlady/dependabot-group-test) where you can already see some dependabot PRs that should have been grouped

**Comment by CandiedCode** [comment]
looks like this hasn't been resolved yet based on @huehnerlady example, where the pr's were opened 18hours ago.

@robaiken can we reopen this issue.

This is causing us pain by increased github action usage, larger aws costs, and decreased in velocity in PR merges.

**Comment by linhr** [comment]
We are also experiencing the issue. Here is our configuration that hasn't changed in the past few months: <https://github.com/lakehq/sail/blob/9b55fe957974ef57431194997b677512c4aaa15e/.github/dependabot.yml>

It can be seen from our PR history that one PR was created for each package upgrade for both npm and cargo.

I assume this is impacting a lot of projects, so it would be great to reopen the issue for visibility in the community.

**Comment by linhr** [comment]
These issues could be related:
* #13210
* #13213

I'm not sure if they are due to the same cause though.

**Comment by levymetal** [comment]
We have grouped patches for `@react-native/*`, but Dependabot is opening individual PRs bumping the minor version for matching dependencies. This is a sample of our config:

```yaml
react-native:
  applies-to: version-updates
  patterns:
    - "@react-native/*"
  update-types:
    - patch
```

I'm wondering if we're misunderstanding what the `update-types` directive actually does. Based on these two GitHub blog articles ([one](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/), [two](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/)), `update-types` is designed to minimise the risk of breaking changes. With this in mind, I would assume that by setting `update-types` to `patch`, this instructs Dependabot to ignore minor/major updates for dependencies within the group.

However, what seems to be happening is that Dependabot will group patches as instructed, but also create individual PRs for minor/major updates to dependencies within the group.

Even after reading the [docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference), it isn't clear which of these behaviours is expected. If we only want Dependabot to perform patches on a group, do we need to separately ignore minor/major update-types as below? If so, this duplication doesn't feel intuitive or optimal, especially when more patterns are involved.

```yaml
groups:
  react-native:
    applies-to: version-updates
    patterns:
      - "@react-native/*"
    update-types:
      - patch
ignore:
  - dependency-name: "@react-native/*"
    update-types:
      - "version-update:semver-minor"
      - "version-update:semver-major"
```

**Comment by huehnerlady** [comment]
Any update on this? This isseu is still closed even though the error still exists?

Of course wee can create a new issue, but it would be helpful if this one could be reopened as it is referenced more and more

**Comment by huehnerlady** [comment]
I am not sure but in my test project it looks like the bug is fixed? 🤔

**Comment by kneumei** [comment]
This is still happening for me

**Comment by CandiedCode** [comment]
when this lands, this should fix the issue I was having
https://github.com/dependabot/dependabot-core/pull/13547

Sharing visibility

**Comment by darren-dooley** [comment]
> [@robsterlini](https://github.com/robsterlini) did you have a chance to make an example repo?

Hi @robaiken, thanks for looking into this.

I can confirm that this is still occurring, so maybe this issue should be reopened. I have created a demo repository here to reproduce the bug:
https://github.com/darren-dooley/dependabot-bug-report/

If you look at the open pull requests, you should see that only `major-upgrades` are being grouped correctly but individual pull requests are being made for any minor/patch upgrades. All of the details are in the README.

Hope this helps with the investigation.

**Comment by robaiken** [comment]
@darren-dooley, could you please create a new issue for this? Group updates is a complex area, and issues with similar symptoms typically have different underlying causes. The user who originally reported this issue experienced a very specific root cause that was introduced by https://github.com/dependabot/dependabot-core/pull/12969 and subsequently resolved by https://github.com/dependabot/dependabot-core/pull/13180. 

Since that fix, I've also added additional group params to the Group Specificity filter: https://github.com/dependabot/dependabot-core/pull/13714. Group specificity was introduced to make our group filtering more deterministic. While the original issue title appears generic, the underlying problem was specific and has been addressed. I'd prefer to maintain separate issues for distinct bugs rather than consolidating them under a general catch-all issue, especially since group problems that appear similar often have entirely different root causes.
