### ISSUE TITLE
Cannot configure commit message case to match commitlint

### ISSUE THREAD

**Issue by alerque** [dependabot/dependabot-core#1666]
My projects' commitlint specifications require both a prefix & scope as well as sentence-case for the actual message. It seems dependabot will use sentence-case when no prefix is used or lower case when it is, but I can't seem to get it to mix and match. [This comment](https://github.com/dependabot/dependabot-core/issues/406#issuecomment-385024411) on a related issue seems to suggest is should be possible, but I can't figure out how.

I'm configuring commitlint using the YAML file option (`.commitlintrc.yaml`) rather than `packages.json` if that makes a difference.

Is there a way to set up the correct casing?

**Comment by alerque** [comment]
This is not stale, no solution has been presented and the problem is ongoing.

**Comment by kewisch** [comment]
Confirming this is still an issue. Would be great if dependabot was aware of commitlint configs and would apply `sentence-case` when it is provided. The message builder code seems to use a static "bump" or "update" string, I've found no use of `upcase_first` that would transform this into sentence case.

Does dependabot have a general policy about adapting behavior based on presence of config files to third party code? I'm guessing keeping that working across versions might be difficult, but maybe commitlint is somewhat in a special place. Alternatively, would it be reasonable to scour past commit messages and adapt to the same style there?

Would a PR on this issue be welcome by the maintainers?

**Comment by kewisch** [comment]
For anyone else finding this and looking for a workaround, see for example https://github.com/agilepathway/label-checker/pull/108/files

**Comment by alerque** [comment]
@kewisch That's cute — and useful if you are okay with giving the bot a free pass to violate project standards :laughing:. Next thing you know you'll be giving the bot that drives your car a free pass to park on your lawn because it can't be taught to stay on the concrete driveway.

**Comment by cyberveseli** [comment]
Hey @alerque did you find solution to this problem?

**Comment by alerque** [comment]
No. So far I have to manually rewrite commit messages for everything dependabot submits, usually by squash-merging with a custom message.

In other news I hear most people's self driving cars usually end up parked on curbs because they can't configure them to get close to the curb without getting on it.

**Comment by deivid-rodriguez** [comment]
I think #5744 should fix this problem!

**Comment by MikeDombo** [comment]
@deivid-rodriguez when should your change take effect? I just had Dependabot recreate a PR, but it still fails the commitlint due to having lines over 100 characters. ex: https://github.com/aws-greengrass/aws-greengrass-logging-java/pull/131

**Comment by deivid-rodriguez** [comment]
The related PR just fixed the commit message case as reported in this issue, there's no change other than that.
