### ISSUE TITLE
ERROR pyenv: version `3.8.3' is not installed

### ISSUE THREAD

**Issue by lee-vg** [dependabot/dependabot-core#2385]
Dependabot was working perfectly and then a few days ago we keep seeing 
```updater | ERROR <job_40565714> pyenv: version `3.8.3' is not installed (set by /home/dependabot/dependabot-updater/tmp/dependabot_20200729-73-18x52h4/.python-version)
updater | ``` in the logs.

We are using python and poetry.

the full error is:
```
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:317:in `run_poetry_command'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:84:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:72:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `chdir'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
updater | ERROR <job_40565714> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:71:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:42:in `latest_resolvable_version'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:250:in `requirements_to_unlock'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:186:in `check_and_create_pull_request'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_40565714> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_40565714> bin/update_files.rb:21:in `<main>'
```

**Comment by feelepxyz** [comment]
@lee-vg this should now be fixed.

**Comment by chris48s** [comment]
Hello. I'm seeing a similar error on all my python projects. I just tried bumping after seeing this post and I'm still getting the error

```
updater | I, [2020-07-29T15:45:19.878602 #72]  INFO -- sentry: ** [Raven] Sending event 8d4e6949d6754503b532430ac18a0e13 to Sentry
  proxy | 2020/07/29 15:45:40 POST https://sentry.io:443/api/1425239/store/
  proxy | 2020/07/29 15:45:40 200 https://sentry.io:443/api/1425239/store/
updater | ERROR <job_41848735> Error processing isort (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_41848735> pyenv: version `3.8.3' is not installed (set by /home/dependabot/dependabot-updater/tmp/dependabot_20200729-72-1qn181c/.python-version)
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:317:in `run_poetry_command'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:84:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:72:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `chdir'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
updater | ERROR <job_41848735> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:71:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:42:in `latest_resolvable_version'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:250:in `requirements_to_unlock'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:186:in `check_and_create_pull_request'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_41848735> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_41848735> bin/update_files.rb:21:in `<main>'
```

Anything I need to do other than 'bump now' to clear this? Is it a different issue?
Thanks

**Comment by feelepxyz** [comment]
@chris48s yeah same issue but we only fixed it in v2 not preview 🤦‍♂️ rolling out the new version again.

**Comment by feelepxyz** [comment]
@chris48s could you try bumping again?

**Comment by chris48s** [comment]
Thanks. That is resolved now :+1: 
I should probably update those projects to use dependabot v2 anyway :smile:

**Comment by Fenkiou** [comment]
Hello, I'm currently experiencing this issue as well with version 0.123.0 with this message `pyenv: version '3.8.5' is not installed`.

Tried with 0.120.3 and no issue. I tried with this version because I thought it could be related to this commit: 43381fa2eb5ad5f1a57c88e04bded2538fe9653b and indeed with 0.120.4 the issue is present

**Comment by jurre** [comment]
> Hello, I'm currently experiencing this issue as well with version 0.123.0 with this message `pyenv: version '3.8.5' is not installed`.
> 
> Tried with 0.120.3 and no issue (well not really but no related to pyenv at least). I tried with this version because I thought it could be related to this commit: [43381fa](https://github.com/dependabot/dependabot-core/commit/43381fa2eb5ad5f1a57c88e04bded2538fe9653b) and indeed with 0.120.4 the issue is present

Thanks @Fenkiou I think https://github.com/dependabot/dependabot-core/pull/2645 should fix it

**Comment by Fenkiou** [comment]
@jurre Thanks, but I still have the issue with `0.123.1` :/

**Comment by jurre** [comment]
The logs indicate you're on `0.118.8` or dependabot-core right? `gems/dependabot-common-0.118.8`

**Comment by Fenkiou** [comment]
@jurre alright my bad! I'm using the `0.123.1` docker image but I cloned that repository : https://github.com/dependabot/dependabot-script and using it directly... so that's a usage issue, not a bug.. There is the corresponding issue in the other repo : https://github.com/dependabot/dependabot-script/issues/477

Sorry for the noise

**Comment by jurre** [comment]
@Fenkiou no worries, happy to hear it's working ✨
