### ISSUE TITLE
Incorect link for numpy's changelog.

### ISSUE THREAD

**Issue by domdfcoding** [dependabot/dependabot-core#2773]
**Package manager/ecosystem**
Pip/Python

**Manifest contents prior to update**
https://github.com/domdfcoding/pyms-agilent/blob/058a8d868cc944a717da53dea3a133c93b085735/requirements.txt

**Updated dependency**
Numpy, from 1.19.3 to 1.19.4

**What you expected to see, versus what you actually saw**
I expected the link to the changelog in the commit message to point to the relevant changelog, but instead it points to https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt, which are instructions on how to release a new version of numpy.
 
**Images of the diff or a link to the PR, issue or logs**
PR: https://github.com/domdfcoding/pyms-agilent/pull/1

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this still a valid / reproducible issue?

Also, this is a package metadata issue... we definitely aren't perfect in our code paths for fetching metadata, but across the ecosystems we support what we've found is that reasonably frequently the problem is the underlying dependency getting bumped publishes wrong metadata.

Anyway, if you're still seeing this let us know, otherwise we should close this.

**Comment by domdfcoding** [comment]
This is still a problem, although now it's pointing to a different file. The target URL is now https://github.com/numpy/numpy/blob/main/doc/RELEASE_WALKTHROUGH.rst

See https://github.com/sphinx-toolbox/seed_intersphinx_mapping/pull/50/commits for a recent example.

I think the issue is due to the ChangelogFinder (code starts [here](https://github.com/dependabot/dependabot-core/blob/69f01216272caf466775d3391ed981795e2aa9d7/common/lib/dependabot/metadata_finders/base/changelog_finder.rb#L13)), which looks for files with "release" in their name, ignoring case. It sees the filename "RELEASE_WALKTHROUGH.rst", and thinks it's the changelog.

https://github.com/dependabot/dependabot-core/blob/69f01216272caf466775d3391ed981795e2aa9d7/common/lib/dependabot/metadata_finders/base/changelog_finder.rb#L123-L139

I don't think it's an issue with numpy's metadata directly, as the only links they provide are:

```
Download-URL: https://pypi.python.org/pypi/numpy
Project-URL: Bug Tracker, https://github.com/numpy/numpy/issues
Project-URL: Documentation, https://numpy.org/doc/1.23
Project-URL: Source Code, https://github.com/numpy/numpy
```

**Comment by abdulapopoola** [comment]
Closing as stale
