### ISSUE TITLE
Superseded pull requests which were assigned a reviewer from a team end up with multiple reviewers from that team

### ISSUE THREAD

**Issue by chrisfosterelli** [dependabot/dependabot-core#4363]
**Package ecosystem**
npm
**Package manager version**
N/A (multiple repositories with multiple versions)
**Language version**
N/A (multiple repositories with multiple versions)
**Manifest location and content prior to update**
`./package.json`
**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    reviewers: 
      - '@TwoStoryRobot/<snip>'
```
**Updated dependency**
N/A
**What you expected to see, versus what you actually saw**
When a dependabot PR is automatically assigned a reviewer from a team, and then that PR is superseded by another PR, I expect the new PR to have the same reviewer assigned.

What I actually see is that dependabot assigns two reviewers to the new PR: one from the prior PR and another randomly selected from the team.
**Native package manager behavior**
N/A
**Images of the diff or a link to the PR, issue or logs**
![image](https://user-images.githubusercontent.com/2072672/139947094-a260253a-61c5-4713-ad33-06bc98bbc37e.png)

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

This issue is pretty old, and we've pushed a lot of bugfixes since then... is this happening for you? If so, how is your `CODEOWNERS` setup?

**Comment by chrisfosterelli** [comment]
@jeffwidman Hey Jeff, thanks for the reply. Yes, we still see this behaviour. We don't have a `CODEOWNERS` file on any of our repos. Let me know if I can provide any additional information

**Comment by icholy** [comment]
I'm running into the same issue. I have the team setup to round-robin assign a single member of the team:
![image](https://user-images.githubusercontent.com/943597/211397019-1313e7eb-3d27-4b2a-8226-1ce3c7af3868.png)
Then in `.github/dependabot.yml` I have the team name as the reviewers:

``` yaml
reviewers:
  - my_org/my_team
```
Here's what happens:
1. The first PR correctly adds a member of the team as a reviewer.
2. The second PR supersedes the first one, and add a different team member as a reviewer.
3. Dependabot then also adds the reviewers from the first PR as a reviewer on the second PR.

**Comment by sekiwakana** [comment]
I have same issue.
Dependabot bring in reviewers from closed PRs marked as "Superseded" to new PRs.

**Comment by Waleed2660** [comment]
Can confirm that still seeing this issue in 2025
