### ISSUE TITLE
Timeout on Docker image

### ISSUE THREAD

**Issue by fertapric** [dependabot/dependabot-core#4575]
**Package ecosystem**
docker

**Package manager version**
v1

**Manifest location and content prior to update**
`/Dockerfile`

**dependabot.yml content**
```yaml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: ".devbox"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
**Updated dependency**
Docker, `hexpm/elixir:1.13.1-erlang-24.2-alpine-3.15.0`

**What you expected to see, versus what you actually saw**
I would expect no errors.

**Images of the diff or a link to the PR, issue or logs**
<details>
<summary>Logs</summary>

```
proxy | time="2021-12-31T05:20:48Z" level=info msg="proxy starting" commit=97925bb09c93ffdb9ffa4337cfa17277d7a43c14
  proxy | 2021/12/31 05:20:48 Listening (:1080)
updater | 2021-12-31T05:20:48.699087432 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2021-12-31T05:20:48.728936192 [250311227:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2021-12-31T05:20:50Z" level=info msg="guest starting" commit=0b0fc6eb1ced505a4a1c1d4892fc2ae3bb5e2549
updater | time="2021-12-31T05:20:50Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=250311227 updater_timeout=45m0s updater_version=0.169.8-64f70c18f6316d0ec64dcb01517df7d98aa0c098
updater | I, [2021-12-31T05:20:51.999901 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_250311227> Starting job processing
  proxy | 2021/12/31 05:20:54 [002] GET https://api.github.com:443/repos/supranode/diskette
  proxy | 2021/12/31 05:20:54 [002] * authenticating github api request
  proxy | 2021/12/31 05:20:54 [002] 200 https://api.github.com:443/repos/supranode/diskette
  proxy | 2021/12/31 05:20:54 [004] GET https://api.github.com:443/repos/supranode/diskette/git/refs/heads/main
  proxy | 2021/12/31 05:20:54 [004] * authenticating github api request
  proxy | 2021/12/31 05:20:54 [004] 200 https://api.github.com:443/repos/supranode/diskette/git/refs/heads/main
  proxy | 2021/12/31 05:20:54 [006] GET https://api.github.com:443/repos/supranode/diskette/contents/.devbox?ref=3f42195947ac9c41b7f89a8c2dda8b0a9a14bfc3
  proxy | 2021/12/31 05:20:54 [006] * authenticating github api request
  proxy | 2021/12/31 05:20:54 [006] 200 https://api.github.com:443/repos/supranode/diskette/contents/.devbox?ref=3f42195947ac9c41b7f89a8c2dda8b0a9a14bfc3
  proxy | 2021/12/31 05:20:54 [008] GET https://api.github.com:443/repos/supranode/diskette/contents/.devbox/Dockerfile?ref=3f42195947ac9c41b7f89a8c2dda8b0a9a14bfc3
  proxy | 2021/12/31 05:20:54 [008] * authenticating github api request
  proxy | 2021/12/31 05:20:54 [008] 200 https://api.github.com:443/repos/supranode/diskette/contents/.devbox/Dockerfile?ref=3f42195947ac9c41b7f89a8c2dda8b0a9a14bfc3
updater | INFO <job_250311227> Finished job processing
updater | time="2021-12-31T05:20:54Z" level=info msg="task complete" container_id=job-250311227-file-fetcher exit_code=0 job_id=250311227 step=fetcher
updater | I, [2021-12-31T05:20:55.619288 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_250311227> Starting job processing
updater | INFO <job_250311227> Starting update job for supranode/diskette
updater | INFO <job_250311227> Checking if hexpm/elixir 1.13.1-erlang-24.2-alpine-3.15.0 needs updating
  proxy | 2021/12/31 05:20:57 [012] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:20:57 [012] 401 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:20:57 [014] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2021/12/31 05:20:57 [014] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2021/12/31 05:20:57 [016] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:02 [018] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:07 [020] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:07 [020] 401 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:07 [022] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2021/12/31 05:21:07 [022] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2021/12/31 05:21:07 [024] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:09 [018] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:09 [018] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:39576: write: broken pipe
  proxy | 2021/12/31 05:21:12 [026] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:14 [024] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:14 [024] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:39582: write: broken pipe
  proxy | 2021/12/31 05:21:14 [016] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:14 [016] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:39574: write: broken pipe
  proxy | 2021/12/31 05:21:17 [028] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:17 [028] 401 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:17 [030] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2021/12/31 05:21:17 [030] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2021/12/31 05:21:17 [032] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:19 [026] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:19 [026] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:39584: write: broken pipe
  proxy | 2021/12/31 05:21:22 [034] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:24 [032] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2021/12/31 05:21:24 [032] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:39590: write: broken pipe
updater | I, [2021-12-31T05:21:27.946275 #8]  INFO -- sentry: ** [Raven] Sending event 7abcec177c104d27a190aba94feee6c1 to Sentry
  proxy | 2021/12/31 05:21:28 [036] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/12/31 05:21:28 [036] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_250311227> Error processing hexpm/elixir (RestClient::Exceptions::ReadTimeout)
updater | ERROR <job_250311227> Timed out reading data from server
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:751:in `rescue in transmit'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:313:in `do_bearer_req'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:269:in `rescue in doreq'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:245:in `doreq'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:26:in `doget'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:65:in `tags'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.169.8/lib/dependabot/docker/update_checker.rb:231:in `tags_from_registry'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.169.8/lib/dependabot/docker/update_checker.rb:173:in `comparable_tags_from_registry'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.169.8/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.169.8/lib/dependabot/docker/update_checker.rb:60:in `latest_version'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:464:in `all_versions_ignored?'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:193:in `check_and_create_pull_request'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_250311227> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_250311227> bin/update_files.rb:22:in `<main>'
updater | INFO <job_250311227> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2021-12-31T05:21:28Z" level=info msg="task complete" container_id=job-250311227-updater exit_code=0 job_id=250311227 step=updater
```
</details>

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried.

This issue is bit old, and we've pushed a lot of infra improvements since then... is this still a valid / reproducible issue?

**Comment by pehbehbeh** [comment]
It is still an issue. I tried with the latest Dependabot version (installed via [Helm Chart](https://gitlab.com/dependabot-gitlab/dependabot)) and the `hexpm/elixir` dependency. I also get the same error:

> Timed out reading data from server

Maybe there is too much data to process? The dependency has a lot of tags.

**Comment by deivid-rodriguez** [comment]
Is there a public repository that reproduces the issue? If not, could you create a minimal one (just manifest and dependabot config).

**Comment by pehbehbeh** [comment]
Here you go: https://github.com/pehbehbeh/dependabot-hexpm-elixir-test

Here are the logs from a few minutes ago:

<details><summary>Dependabot Logs</summary>

```
  proxy | time="2022-09-07T09:51:49Z" level=info msg="proxy starting" commit=b031647dc5f52d8120800fc16337727989cb9be0
  proxy | 2022/09/07 09:51:49 Listening (:1080)
updater | 2022-09-07T09:51:49.738666435 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-09-07T09:51:49.768891286 [454108170:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-09-07T09:51:51Z" level=info msg="guest starting" commit=e4835da832fa8b0474739135799a274067e98471
updater | time="2022-09-07T09:51:51Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=454108170 updater_timeout=45m0s updater_version=33a13203505a9d1da9d5b5c06a35c7440de01f41
updater | I, [2022-09-07T09:51:53.437599 #6]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_454108170> Starting job processing
  proxy | 2022/09/07 09:51:56 [002] GET https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test
  proxy | 2022/09/07 09:51:56 [002] * authenticating github api request
  proxy | 2022/09/07 09:51:56 [002] 200 https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test
  proxy | 2022/09/07 09:51:56 [004] GET https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test/git/refs/heads/main
  proxy | 2022/09/07 09:51:56 [004] * authenticating github api request
  proxy | 2022/09/07 09:51:56 [004] 200 https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test/git/refs/heads/main
  proxy | 2022/09/07 09:51:56 [006] GET https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test/contents/?ref=6a66c38b65cfb5d12ee8de630bff72e9de5c53a0
  proxy | 2022/09/07 09:51:56 [006] * authenticating github api request
  proxy | 2022/09/07 09:51:56 [006] 200 https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test/contents/?ref=6a66c38b65cfb5d12ee8de630bff72e9de5c53a0
  proxy | 2022/09/07 09:51:56 [008] GET https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test/contents/Dockerfile?ref=6a66c38b65cfb5d12ee8de630bff72e9de5c53a0
  proxy | 2022/09/07 09:51:56 [008] * authenticating github api request
  proxy | 2022/09/07 09:51:56 [008] 200 https://api.github.com:443/repos/pehbehbeh/dependabot-hexpm-elixir-test/contents/Dockerfile?ref=6a66c38b65cfb5d12ee8de630bff72e9de5c53a0
updater | INFO <job_454108170> Finished job processing
updater | time="2022-09-07T09:51:56Z" level=info msg="task complete" container_id=job-454108170-file-fetcher exit_code=0 job_id=454108170 step=fetcher
updater | I, [2022-09-07T09:51:57.658401 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
updater | INFO <job_454108170> Starting job processing
updater | INFO <job_454108170> Starting update job for pehbehbeh/dependabot-hexpm-elixir-test
updater | INFO <job_454108170> Checking if hexpm/elixir 1.13.4-erlang-25.0.4-alpine-3.16.1 needs updating
  proxy | 2022/09/07 09:52:00 [012] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:00 [012] 401 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:00 [014] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2022/09/07 09:52:00 [014] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2022/09/07 09:52:00 [016] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:05 [018] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:08 [016] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:08 [016] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:44708: write: broken pipe
  proxy | 2022/09/07 09:52:10 [020] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:10 [020] 401 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:10 [022] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2022/09/07 09:52:10 [022] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2022/09/07 09:52:10 [024] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:13 [018] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:13 [018] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:41840: write: broken pipe
  proxy | 2022/09/07 09:52:15 [026] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:18 [024] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:18 [024] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:45680: write: broken pipe
  proxy | 2022/09/07 09:52:20 [028] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:20 [028] 401 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:20 [030] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2022/09/07 09:52:20 [030] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Ahexpm%2Felixir%3Apull
  proxy | 2022/09/07 09:52:20 [032] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:23 [026] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:23 [026] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:45690: write: broken pipe
  proxy | 2022/09/07 09:52:25 [034] GET https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:28 [032] 200 https://registry.hub.docker.com:443/v2/hexpm/elixir/tags/list
  proxy | 2022/09/07 09:52:28 [032] WARN: Cannot write TLS response body from mitm'd client: write tcp 192.168.1.1:1080->192.168.1.2:34102: write: broken pipe
updater | I, [2022-09-07T09:52:30.739235 #8]  INFO -- sentry: ** [Raven] Sending event 099fe69491ce4b43a8ac62a6f5129395 to Sentry
  proxy | 2022/09/07 09:52:30 [036] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/09/07 09:52:31 [036] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_454108170> Error processing hexpm/elixir (RestClient::Exceptions::ReadTimeout)
updater | ERROR <job_454108170> Timed out reading data from server
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:751:in `rescue in transmit'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.12.0/lib/registry/registry.rb:337:in `do_bearer_req'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.12.0/lib/registry/registry.rb:293:in `rescue in doreq'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.12.0/lib/registry/registry.rb:269:in `doreq'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.12.0/lib/registry/registry.rb:26:in `doget'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.12.0/lib/registry/registry.rb:80:in `tags'
updater | ERROR <job_454108170> /home/dependabot/docker/lib/dependabot/docker/update_checker.rb:230:in `tags_from_registry'
updater | ERROR <job_454108170> /home/dependabot/docker/lib/dependabot/docker/update_checker.rb:172:in `comparable_tags_from_registry'
updater | ERROR <job_454108170> /home/dependabot/docker/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
updater | ERROR <job_454108170> /home/dependabot/docker/lib/dependabot/docker/update_checker.rb:60:in `latest_version'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:512:in `all_versions_ignored?'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:216:in `check_and_create_pull_request'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:102:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:73:in `block in run'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:73:in `each'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:73:in `run'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_454108170> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_454108170> bin/update_files.rb:22:in `<main>'
updater | INFO <job_454108170> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-09-07T09:52:31Z" level=info msg="task complete" container_id=job-454108170-updater exit_code=0 job_id=454108170 step=updater
```

</details>

**Comment by jeffwidman** [comment]
Thanks @pehbehbeh very helpful.

I think @pavera may have just fixed this in https://github.com/dependabot/dependabot-core/pull/5674. 

I expect it'll get deployed sometime this week, so can you circle back next week and let us know whether you're still seeing issues?

**Comment by jeffwidman** [comment]
Actually, looks like this will be deployed on GitHub production within the next few hours, so I'm going to close as I expect this is fixed. If for some reason you're still seeing it after tonight, please comment and we can re-open.

**Comment by pehbehbeh** [comment]
The timeout is gone. 👍 

Unfortunately Dependabot ist not able to parse the multi version image tag. 

```
updater | INFO <job_469484217> Latest version is 1.13.4-erlang-25.0.4-alpine-3.16.1
updater | INFO <job_469484217> No update needed for hexpm/elixir 1.13.4-erlang-25.0.4-alpine-3.16.1
```

This problem is already beeing discussed in #5708 #2692 and #4329.

**Comment by jeffwidman** [comment]
Thanks for circling back to let us know the timeout is gone. As far as the others, well, PR's are always welcome or we'll get to it as we have time/capacity.
