### ISSUE TITLE
Error: Dependabot can't parse your package-lock.json

### ISSUE THREAD

**Issue by jlowcs** [dependabot/dependabot-core#5099]
**Package ecosystem**
npm
**Package manager version**
npm 8.1.2
**Language version**
node 16.13.2
**Manifest location and content before the Dependabot update**
`/package.json` contains private dependencies
**dependabot.yml content**
```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.ACCESS_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - npm-github
    schedule:
      interval: daily
    open-pull-requests-limit: 10
```
**What you expected to see, versus what you actually saw**
Before recently (2 days at max), dependabot was running properly.
But then, it started failing in some of our repositories that have private dependencies.
![image](https://user-images.githubusercontent.com/3777724/166944832-cab63823-9154-468a-9808-6ab2a4276b8d.png)

**Comment by jlowcs** [comment]
might be related to https://github.com/dependabot/dependabot-core/issues/5100

**Comment by dlobato** [comment]
We have a similar issue on a repository with no private dependencies, in our case with composer.lock file:
![image](https://user-images.githubusercontent.com/1379455/166968018-399bc400-26ba-46d1-ba24-6ab74f3563ed.png)

Our composer.lock file is 2.3MB and I was wondering if this change might be behind the issue: https://github.blog/changelog/2022-05-03-increased-file-size-limit-when-retrieving-file-contents-via-rest-api/

It was working just fine 2 days ago.

**Comment by WIStudent** [comment]
I am also seeing this error since yesterday in a private repository. The package-lock.json only contains public npm dependencies, but it is 1.3MB big, supporting the theory that it is caused by the API size limit change.

**Comment by pcaversaccio** [comment]
Having the same issue in my public repo here: https://github.com/pcaversaccio/create2deployer/security/dependabot/52. See also in the community forum [here](https://github.community/t/dependabot-errors-when-using-separate-config-entries-for-different-target-branches/248764). Previously everything was working fine.

**Comment by bissolli** [comment]
Running into the same issue in 4 different repos.

**Comment by cansin** [comment]
Facing the same issue with a 2.4 MB package-lock.json on a private repo.

**Comment by chris48s** [comment]
We got this the other day. Public repo with only public dependencies.

- repo: https://github.com/badges/shields (public)
- lockfile 1.95 MB

<details>
    <summary>log output</summary>
<pre>
  proxy | time="2022-05-06T12:00:04Z" level=info msg="proxy starting" commit=d0e8fc9c52e08bf359a8a4cff6deb91b01c23136
  proxy | 2022/05/06 12:00:04 Listening (:1080)
updater | 2022-05-06T12:00:04.964431583 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-05-06T12:00:04.984752430 [361512275:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-05-06T12:00:06Z" level=info msg="guest starting" commit=d54c1f07420d2f98b700854f969f92bffb6a9ded
updater | time="2022-05-06T12:00:06Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=361512275 updater_timeout=45m0s updater_version=0.184.0-90a199ddb668cf5d41b3b630375b1d042908b04b
updater | I, [2022-05-06T12:00:07.899572 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
updater | Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_361512275> Starting job processing
  proxy | 2022/05/06 12:00:10 [002] GET https://api.github.com:443/repos/badges/shields
  proxy | 2022/05/06 12:00:10 [002] * authenticating github api request
  proxy | 2022/05/06 12:00:10 [002] 200 https://api.github.com:443/repos/badges/shields
  proxy | 2022/05/06 12:00:10 [004] GET https://api.github.com:443/repos/badges/shields/git/refs/heads/master
  proxy | 2022/05/06 12:00:10 [004] * authenticating github api request
  proxy | 2022/05/06 12:00:10 [004] 200 https://api.github.com:443/repos/badges/shields/git/refs/heads/master
  proxy | 2022/05/06 12:00:10 [006] GET https://api.github.com:443/repos/badges/shields/contents/package.json?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [006] * authenticating github api request
  proxy | 2022/05/06 12:00:10 [006] 200 https://api.github.com:443/repos/badges/shields/contents/package.json?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [008] GET https://api.github.com:443/repos/badges/shields/contents/?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [008] * authenticating github api request
  proxy | 2022/05/06 12:00:10 [008] 200 https://api.github.com:443/repos/badges/shields/contents/?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [010] GET https://api.github.com:443/repos/badges/shields/contents/package-lock.json?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [010] * authenticating github api request
  proxy | 2022/05/06 12:00:10 [010] 200 https://api.github.com:443/repos/badges/shields/contents/package-lock.json?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [012] GET https://api.github.com:443/repos/badges/shields/contents/badge-maker/package.json?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
  proxy | 2022/05/06 12:00:10 [012] * authenticating github api request
  proxy | 2022/05/06 12:00:10 [012] 200 https://api.github.com:443/repos/badges/shields/contents/badge-maker/package.json?ref=4c8a72434b90b680dd011d284bcb47f994ee4131
updater | INFO <job_361512275> Finished job processing
updater | time="2022-05-06T12:00:10Z" level=info msg="task complete" container_id=job-361512275-file-fetcher exit_code=0 job_id=361512275 step=fetcher
updater | I, [2022-05-06T12:00:11.802264 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
updater | Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_361512275> Starting job processing
updater | INFO <job_361512275> Starting update job for badges/shields
updater | INFO <job_361512275> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-05-06T12:00:13Z" level=info msg="task complete" container_id=job-361512275-updater exit_code=0 job_id=361512275 step=updater
</pre>
</details>

Let us know if there is any more info we can provide to help.

**Comment by yashash1511** [comment]
facing this same issue on multiple repos

**Comment by NathSoM** [comment]
Can confirm, still getting the same error on my lockfile.

**Comment by jakecoffman** [comment]
The release with this fix just landed in production so it should be working now.

Thanks for all the examples, that makes it easy to verify!

**Comment by yashash1511** [comment]
> The release with this fix just landed in production so it should be working now.

yes it works now thank you

**Comment by Anton-Aracor** [comment]
@jakecoffman I still see error similar to mentioned above, but for Python code with Poetry file. It tells that it can't parse it.

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/4c32d9e3-5c54-43c7-b8b0-51867d6f5202">

Maybe our file also counted as "BIG" for GitHub and can't be parsed. But I ran the `parser.py` file and it parses my `pyproject.toml` file just fine.
