### ISSUE TITLE
Dependabot dropped several hashes from poetry.lock

### ISSUE THREAD

**Issue by roniemartinez** [dependabot/dependabot-core#5351]
Running `poetry lock --no-update` reverts these changes and brings back the hashes.

**Package ecosystem**
pip/python - poetry

**Package manager version**

**Language version**

**Manifest location and content before the Dependabot update**

**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**

**Native package manager behavior**

**Images of the diff or a link to the PR, issue, or logs**
https://github.com/roniemartinez/dude/pull/188/files
![image](https://user-images.githubusercontent.com/2573537/178005148-2cc2544b-b3a5-4079-b491-5d0b0e07cf66.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by mkniewallner** [comment]
Issue is not with Dependabot, but something related to Poetry.
Recently released version [1.1.14](https://github.com/dependabot/dependabot-core/pull/5352) solves the issue, so made https://github.com/dependabot/dependabot-core/pull/5352, since Dependabot won't make a PR before a few hours.

You can find more details about the issue in https://github.com/python-poetry/poetry/pull/5972, but in the meantime, Dependabot will basically not be able to lock correctly until https://github.com/dependabot/dependabot-core/pull/5352 is merged and a new version is released (but you can manually lock dependencies yourself in the meantime, if you use `1.1.14`).

**Comment by roniemartinez** [comment]
@mkniewallner Thanks for writing a fix.

**Comment by mkniewallner** [comment]
Didn't test it myself, but [a new version](https://github.com/dependabot/dependabot-core/blob/main/CHANGELOG.md#v01963-12-july-2022) of Dependabot has been released, including a bump of Poetry to `1.1.14`, so this should fix the missing hashes.

**Comment by levrik** [comment]
@mkniewallner It doesn't seem to be online on GitHub yet. I let Dependabot recreate all open PRs but hashes were still missing.
