### ISSUE TITLE
Dependabot does not locate new alpine image versions for Ruby Alpine docker images

### ISSUE THREAD

**Issue by mitchdawson1982** [dependabot/dependabot-core#7320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Manifest location and content before the Dependabot update

  - package-ecosystem: "docker"
    directory: "/dns-service"
    schedule:
      interval: "daily"

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/dns-service/metrics"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/dns-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"

### Updated dependency

Update logs
  proxy | 2023/05/13 00:00:02 proxy starting, commit: d719b9b9871e853c5fd63bf3552f3f857d979f3c
  proxy | 2023/05/13 00:00:02 Listening (:1080)
updater | 2023-05-13T00:00:03.453347814 [662241047:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-05-13T00:00:08Z" level=info msg="guest starting" commit=8ab4a20db815b67034070152643b9878c12b051d
updater | time="2023-05-13T00:00:08Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=662241047 updater_timeout=45m0s updater_version=49704c16cb0893c0ab8c5f884471c324baf39b83-docker
updater | 2023/05/13 00:00:13 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/13 00:00:18 INFO <job_662241047> Starting job processing
  proxy | 2023/05/13 00:00:18 [002] GET https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server
  proxy | 2023/05/13 00:00:18 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/05/13 00:00:19 [002] 200 https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server
  proxy | 2023/05/13 00:00:19 [004] GET https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server/git/refs/heads/main
  proxy | 2023/05/13 00:00:19 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/05/13 00:00:19 [004] 200 https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server/git/refs/heads/main
  proxy | 2023/05/13 00:00:19 [006] GET https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server/contents/dns-service?ref=932b89ecd21bdb4b02630442cd4c0bdae428862b
  proxy | 2023/05/13 00:00:19 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/05/13 00:00:19 [006] 200 https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server/contents/dns-service?ref=932b89ecd21bdb4b02630442cd4c0bdae428862b
  proxy | 2023/05/13 00:00:19 [008] GET https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server/contents/dns-service/Dockerfile?ref=932b89ecd21bdb4b02630442cd4c0bdae428862b
  proxy | 2023/05/13 00:00:19 [008] * authenticating github api request with token for api.github.com
  proxy | 2023/05/13 00:00:19 [008] 200 https://api.github.com:443/repos/ministryofjustice/staff-device-dns-server/contents/dns-service/Dockerfile?ref=932b89ecd21bdb4b02630442cd4c0bdae428862b
updater | 2023/05/13 00:00:19 INFO <job_662241047> Finished job processing
updater | time="2023-05-13T00:00:19Z" level=info msg="task complete" container_id=job-662241047-file-fetcher exit_code=0 job_id=662241047 step=fetcher
updater | 2023/05/13 00:00:20 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/13 00:00:22 INFO <job_662241047> Starting job processing
updater | 2023/05/13 00:00:22 INFO <job_662241047> Starting update job for ministryofjustice/staff-device-dns-server
updater | 2023/05/13 00:00:22 INFO <job_662241047> Checking all dependencies for version updates...
updater | 2023/05/13 00:00:22 INFO <job_662241047> Checking if ruby 3.2.2-alpine3.16 needs updating
  proxy | 2023/05/13 00:00:22 [014] GET https://registry.hub.docker.com:443/v2/library/ruby/tags/list
  proxy | 2023/05/13 00:00:22 [014] 401 https://registry.hub.docker.com:443/v2/library/ruby/tags/list
  proxy | 2023/05/13 00:00:23 [016] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fruby%3Apull&account
  proxy | 2023/05/13 00:00:23 [016] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fruby%3Apull&account
  proxy | 2023/05/13 00:00:23 [018] GET https://registry.hub.docker.com:443/v2/library/ruby/tags/list
  proxy | 2023/05/13 00:00:24 [018] 200 https://registry.hub.docker.com:443/v2/library/ruby/tags/list
  proxy | 2023/05/13 00:00:24 [020] HEAD https://registry.hub.docker.com:443/v2/library/ruby/manifests/latest
  proxy | 2023/05/13 00:00:24 [020] 401 https://registry.hub.docker.com:443/v2/library/ruby/manifests/latest
  proxy | 2023/05/13 00:00:24 [022] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fruby%3Apull&account
  proxy | 2023/05/13 00:00:25 [022] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fruby%3Apull&account
  proxy | 2023/05/13 00:00:25 [024] HEAD https://registry.hub.docker.com:443/v2/library/ruby/manifests/latest
  proxy | 2023/05/13 00:00:25 [024] 200 https://registry.hub.docker.com:443/v2/library/ruby/manifests/latest
  proxy | 2023/05/13 00:00:25 [026] HEAD https://registry.hub.docker.com:443/v2/library/ruby/manifests/3.2.2
  proxy | 2023/05/13 00:00:25 [026] 401 https://registry.hub.docker.com:443/v2/library/ruby/manifests/3.2.2
  proxy | 2023/05/13 00:00:25 [028] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fruby%3Apull&account
  proxy | 2023/05/13 00:00:25 [028] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fruby%3Apull&account
  proxy | 2023/05/13 00:00:25 [030] HEAD https://registry.hub.docker.com:443/v2/library/ruby/manifests/3.2.2
  proxy | 2023/05/13 00:00:25 [030] 200 https://registry.hub.docker.com:443/v2/library/ruby/manifests/3.2.2
updater | 2023/05/13 00:00:25 INFO <job_662241047> Latest version is 3.2.2-alpine3.16
updater | 2023/05/13 00:00:25 INFO <job_662241047> No update needed for ruby 3.2.2-alpine3.16
updater | 2023/05/13 00:00:25 INFO <job_662241047> Finished job processing
updater | time="2023-05-13T00:00:25Z" level=info msg="task complete" container_id=job-662241047-updater exit_code=0 job_id=662241047 step=updater

### What you expected to see, versus what you actually saw

# Dependabot Behaviour
Dependabot fails to detect ruby alpine images later than the current in use (3.2.2-alpine3.16).

# Expected Behaviour
Dependabot should detect 3.2.2-alpine3.18 as being available for upgrade.

### Native package manager behavior

N/A

### Images of the diff or a link to the PR, issue, or logs

N/A

**Comment by honeyankit** [comment]
@mitchdawson1982 , This issue has been fixed. Try to manually run the Dependabot version update again.

**Comment by deivid-rodriguez** [comment]
I _think_ this is not actually fixed? We still don't consider the `-alpine3.16` part as part of the version so we can't update it, right?
