### ISSUE TITLE
Adding individual package ignores via grouped PRs is not working.

### ISSUE THREAD

**Issue by Vossekop** [dependabot/dependabot-core#7910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### dependabot.yml content

``` yml
version: 2

updates:
  - package-ecosystem: nuget
    directory: "/Server"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Amsterdam"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    reviewers:
      - "priva-platform/groot"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/Tests/Cloud"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Amsterdam"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    reviewers:
      - "priva-platform/groot"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/Tests/Local"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Amsterdam"
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "nuget"
      include: "scope"
    reviewers:
      - "priva-platform/groot"
    open-pull-requests-limit: 10
```

### Updated dependency

Package | Update
-- | --
Microsoft.EntityFrameworkCore | 7.0.9 to 7.0.10
Microsoft.EntityFrameworkCore.Design | 7.0.9 to 7.0.10
Microsoft.AspNetCore.DataProtection.EntityFrameworkCore | 6.0.20 to 7.0.10
Microsoft.EntityFrameworkCore.SqlServer | 7.0.9 to 7.0.10
Microsoft.AspNetCore.Authentication.OpenIdConnect | 6.0.20 to 7.0.10
dotnet-ef | 7.0.9 to 7.0.10

### What you expected to see, versus what you actually saw

With this set of updates I actually want to ignore 2 of them, I try to do this using the following commands:

`@dependabot ignore Microsoft.AspNetCore.DataProtection.EntityFrameworkCore major version`
`@dependabot ignore Microsoft.AspNetCore.Authentication.OpenIdConnect major version`

I expect dependabot to give me a thumbsup and recreate the PR without the specified major version of these packages. However, dependabot does not respond at all. I've tried this by doing each command in a separate comment in the PR or both together in one comment, neither works.

Other commands do work, for instance: `@dependabot show Microsoft.AspNetCore.DataProtection.EntityFrameworkCore ignore conditions` responds with: No ignore conditions found for the dependency microsoft.aspnetcore.dataprotection.entityframeworkcore

One thing of note is that we use GitHub EMU (Enterprise Managed Users).

**Comment by Nishnha** [comment]
Hi this was broken but should now be fixed. Could you attempt to run the ignore conditions once again?

**Comment by Vossekop** [comment]
I am afraid it is still not working. Does it need the PR to be created with the new version?
![image](https://github.com/dependabot/dependabot-core/assets/8823799/7bf848ea-6774-493f-b389-1dc5e0760a45)

**Comment by Nishnha** [comment]
Thanks for the screenshot @Vossekop. I tracked this down to being an issue with casing. If you run the command `@dependabot ignore microsoft.aspnetcore.dataprotection.entityframeworkcore major version` (with the dependency name in lowercase) it should work.

Fix coming soon.

**Comment by Vossekop** [comment]
Thanks for the reply @Nishnha, I thought I had tried it lower case already as well, but you got me doubting so I tried it again. It did not work however. Even tried with two separate packages just to be sure:

![image](https://github.com/dependabot/dependabot-core/assets/8823799/9b665466-142a-4ecb-a105-f1229bc96d04)

These packages are in the list of packages in the PR I'm currently testing with (which is not the one from the starting post of this issue).

**Comment by coderroggie** [comment]
Similar setup with an EMU account but the package is one from datadog:
`
@dependabot ignore @datadog/mobile-react-native minor version
`

<img width="837" alt="Screenshot 2023-08-31 at 6 03 12 AM" src="https://github.com/dependabot/dependabot-core/assets/1376024/45dadde5-5193-42f1-b1d0-3b7cb1b987f7">

Tried many different variations to get it to work as well as a co-worker trying many variations and we weren't able to get the right incantation 😞   We've backed out of the grouping for now until this is fixed.

**Comment by Vossekop** [comment]
Interestingly we don't even get a "Sorry... <etc.>" message indicating that the command is not valid.

**Comment by Vossekop** [comment]
@Nishnha it is still behaving somewhat flaky, some ignores trigger the PR being closed with this message "Looks like these dependencies are updatable in another way, so this is no longer needed." while other PRs seem to be updated with the requested change (without the PR description being updated). When I add two ignores in quick succession it does not pick up the second one either. It would be a lot easier if you could put two ignore commands in one message.

But if I wait long enough between ignore commands it will either recreate the PR or update it with the correct change. I will just have to be patient. Which is unfortunate, because that makes dependabot still not as smooth as it could be. But better then it was before.

**Comment by Nishnha** [comment]
Oops I did not mean to close out the issue. I had merged a fix that was linked to this issue and it seemed to have closed it.

On that note, `@dependabot ignore Microsoft.AspNetCore.DataProtection.EntityFrameworkCore major version` should work. Could you try it again and let me know?

> some ignores trigger the PR being closed with this message "Looks like these dependencies are updatable in another way, so this is no longer needed." while other PRs seem to be updated with the requested change (without the PR description being updated)

I also noticed some flakey behavior with ignores. I'll look into these 2 issues you pointed out, but I think the first one may be desired behavior.

When a PR receives a new ignore condition Dependabot will try to re-run the update, but if a dependency is removed from the update, Dependabot will close the current PR and try to open a new one since it considers it a different PR.

> When I add two ignores in quick succession it does not pick up the second one either

I think if Dependabot reacted to ignore rules with a 👍🏾 reaction it might be easier to tell whether a command was actually recognized - I'll look into adding this. I'm not sure why the second ignore command was not picked up though.

> When I add two ignores in quick succession it does not pick up the second one either. It would be a lot easier if you could put two ignore commands in one message.

This makes a lot of sense as a feature request and I'll file an issue on our backlog for it. 
In the meantime, if you want to ignore multiple dependencies quickly, you can [add the ignores directly](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) to your repo's `dependabot.yml` and then re-check for a Dependabot update by going to the Insights tab > Dependency Graph > Dependabot > last checked X hours ago > check for updates

**Comment by Nishnha** [comment]
I'm going to close this issue out as fixed. If you still encounter this issue please leave a comment and we can reopen/reinvestigate.
