### ISSUE TITLE
Dependabot no longer updates NuGet packages in a repository with only a Directory.Packages.props file

### ISSUE THREAD

**Issue by martincostello** [dependabot/dependabot-core#8590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

.NET SDK 8.0.100

### Language version

C# 12

### Manifest location and content before the Dependabot update

`Directory.Packages.props`

```xml
<Project>
  <ItemGroup>
    <PackageVersion Include="coverlet.msbuild" Version="6.0.0" />
    <PackageVersion Include="GitHubActionsTestLogger" Version="2.3.3" />
    <PackageVersion Include="JustEat.HttpClientInterception" Version="4.0.0" />
    <PackageVersion Include="MartinCostello.Logging.XUnit" Version="0.3.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="NSubstitute" Version="5.1.0" />
    <PackageVersion Include="ReportGenerator" Version="5.2.0" />
    <PackageVersion Include="Shouldly" Version="4.2.1" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.507" />
    <PackageVersion Include="xunit" Version="2.6.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.4" />
    <PackageVersion Include="Xunit.SkippableFact" Version="1.4.13" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup Condition=" '$(IsTestProject)' == 'true' ">
    <PackageReference Include="coverlet.msbuild" PrivateAssets="All" />
    <PackageReference Include="GitHubActionsTestLogger" PrivateAssets="All" />
    <PackageReference Include="ReportGenerator" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

### dependabot.yml content

```yaml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  groups:
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/src/CHANGE_ME"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
```

### Updated dependency

None.

### What you expected to see, versus what you actually saw

I have a private template repository where various repo boilerplate files to set up a new project (library, an app, whatever) exist. This repository intentionally doesn't contain any `.csproj` files, but does contain a `Directory.Build.props` file with the `PackageVersion` elements for various NuGet packages that are always nearly present in my repositories, such as the .NET test SDK, xunit, etc.

Previously, Dependabot would update the package versions in the file:

![image](https://github.com/dependabot/dependabot-core/assets/1439341/0320e9ee-e179-421d-84d0-b78aa6eb49b6)

Now it errors:

```text
Dependabot couldn't find a <anything>.(cs|vb|fs)proj
Dependabot requires a .(cs|vb|fs)proj to evaluate your .NET dependencies. It had expected to find one at the path: /<anything>.(cs|vb|fs)proj.
```

Ideally, Dependabot would still be able to process the package versions without requiring any project files that reference them to be present.

**Comment by abdulapopoola** [comment]
@martincostello ; it does seem this should be fixed in this PR by @brettfo : https://github.com/dependabot/dependabot-core/pull/8842. Can you please confirm if it still repros?

**Comment by willbush** [comment]
I just tried running dependabot from (really hard to find):

Insights > Dependency graph > dependabot tab > Recent update jobs > check for updates

I'm still getting

```
Dependabot couldn't find a <anything>.(cs|vb|fs)proj

Dependabot requires a .(cs|vb|fs)proj to evaluate your .NET dependencies. It had expected to find one at the path: /<anything>.(cs|vb|fs)proj.
```

**Comment by abdulapopoola** [comment]
Seems like Dependabot can't pick up the config file. We'll have to investigate

**Comment by abdulapopoola** [comment]
Yes please, that'll help a lot

**Comment by willbush** [comment]
@abdulapopoola here you go https://github.com/willbush/dependabot-cpm-updates

It's a sort of basic monorepo with a `Services` folder with two projects inside `HelloA` and `HelloB` made with `dotnet new web -o HelloA`.

You can run one of the projects like this from the command line with [dotnet](https://dotnet.microsoft.com/en-us/download):

```sh
Services/HelloA/HelloA on  main via .NET v8.0.201 🎯 net8.0
❯ dotnet run
Building...
[21:01:11 INF] hi A
[21:01:11 WRN] hi A
[21:01:11 ERR] hi A
[21:01:11 FTL] hi A
[21:01:11 INF] Now listening on: http://localhost:5068
[21:01:11 INF] Application started. Press Ctrl+C to shut down.
[21:01:11 INF] Hosting environment: Development
[21:01:11 INF] Content root path: /home/will/code/dependabot-cpm-updates/Services/HelloA/HelloA
^C[21:01:15 INF] Application is shutting down...
```

In the `Directory.Packages.props` these versions of `Serilog*` are out-of-date:

```xml
<PackageVersion Include="Serilog" Version="3.1.1" />
<PackageVersion Include="Serilog.AspNetCore" Version="8.0.1" />
<PackageVersion Include="Serilog.Sinks.Console" Version="5.0.1" />
```

**Comment by brettfo** [comment]
@martincostello I've been thinking about this for a bit and I don't think this is a scenario that dependabot should directly support.  Just the package versions in `Directory.Packages.props` aren't enough to perform updates, we also need to know the value of `<TargetFramework>` in a `.csproj` and if that's not present, we have no way of knowing if a package update is possible.  I realize it used to produce PRs in the past, but I would argue that was incorrect due to the lack of TFM.

What are your thoughts about adding a sentinel `.csproj` to the repo with the relevant `<PackageReference>` elements?  This should allow the updater to have a valid TFM against which to check for package compatibility.

**Comment by martincostello** [comment]
No problem - sure that's something I can try out and report back on.

Yeah, I figured it's not that usual a configuration, but as it worked before I figured best to raise an issue on it.

**Comment by martincostello** [comment]
I've set that up, but it's running into #9245.

**Comment by abdulapopoola** [comment]
@martincostello ; #9245 should be fixed now; can you please retry so we can make progress on #8590 :)

**Comment by willbush** [comment]
Is [this](https://github.com/willbush/dependabot-cpm-updates/blob/main/Dependabot.hack.csproj) what is meant by a sentinel `.csproj`?

I'm getting this error:

https://github.com/willbush/dependabot-cpm-updates/network/updates/799587273

I'm guessing you can't see that link so here is the output with a bunch of the `proxy` lines elided:

```
Dependabot encountered an unknown error

Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.
Troubleshoot Dependabot errors
Update logs
  proxy | 2024/03/13 18:19:31 proxy starting, commit: cf8623577dad71c128f219df2b27df6de35b909d
  proxy | 2024/03/13 18:19:31 Listening (:1080)
updater | 2024-03-13T18:19:31.614977125 [799587273:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-03-13T18:19:33Z" level=info msg="guest starting" commit=6ee2dfdd9de690457a831bc6c065b2ec4acdd0b7
updater | time="2024-03-13T18:19:33Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=799587273 updater_timeout=45m0s updater_version=51238f22ab486eae8d90ca0a9ec88d7353da24bc-nuget
updater | 2024/03/13 18:19:37 INFO <job_799587273> Starting job processing
updater | 2024/03/13 18:19:37 INFO <job_799587273> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[{"applies-to":"version-updates","name":"nuget-dependencies","rules":{"patterns":["*"]}}],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"nuget","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":null,"directory":"/.","hostname":"github.com","provider":"github","repo":"willbush/dependabot-cpm-updates"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/03/13 18:19:38 [002] GET https://github.com:443/willbush/dependabot-cpm-updates/info/refs?service=git-upload-pack
  proxy | 2024/03/13 18:19:38 [002] * authenticating git server request (host: github.com)
  ...
updater | 2024/03/13 18:19:38 INFO <job_799587273> Finished job processing
updater | time="2024-03-13T18:19:38Z" level=info msg="task complete" container_id=job-799587273-file-fetcher exit_code=0 job_id=799587273 step=fetcher
updater | 2024/03/13 18:19:41 INFO <job_799587273> Starting job processing
  proxy | 2024/03/13 18:19:41 [008] GET https://api.nuget.org:443/v3/registration5-gz-semver2/mstest.testadapter/index.json
  proxy | 2024/03/13 18:19:41 [008] 200 https://api.nuget.org:443/v3/registration5-gz-semver2/mstest.testadapter/index.json
  ...
updater | 2024/03/13 18:19:52 INFO <job_799587273> Starting grouped update job for willbush/dependabot-cpm-updates
updater | 2024/03/13 18:19:52 INFO <job_799587273> Found 1 group(s).
updater | 2024/03/13 18:19:52 INFO <job_799587273> Starting update group for 'nuget-dependencies'
updater | 2024/03/13 18:19:52 INFO <job_799587273> Checking if MSTest.TestAdapter 3.1.1 needs updating
updater | 2024/03/13 18:19:52 INFO <job_799587273> Filtered out 34 pre-release versions
  proxy | 2024/03/13 18:19:52 [278] GET https://api.nuget.org:443/v3-flatcontainer/mstest.testadapter/3.1.1/mstest.testadapter.nuspec
  proxy | 2024/03/13 18:19:52 [278] 200 https://api.nuget.org:443/v3-flatcontainer/mstest.testadapter/3.1.1/mstest.testadapter.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETStandard2.0 .NETFramework4.6.2 UAP10.0 .NETCoreApp3.1 net6.0 --verbose
updater | The package is compatible.
  proxy | 2024/03/13 18:19:53 [282] GET https://api.nuget.org:443/v3-flatcontainer/mstest.testadapter/3.2.2/mstest.testadapter.nuspec
  proxy | 2024/03/13 18:19:53 [282] 200 https://api.nuget.org:443/v3-flatcontainer/mstest.testadapter/3.2.2/mstest.testadapter.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETStandard2.0 .NETFramework4.6.2 UAP10.0 .NETCoreApp3.1 net6.0 net7.0 net8.0 --verbose
updater | The package is compatible.
updater | 2024/03/13 18:19:53 INFO <job_799587273> Latest version is 3.2.2
updater | 2024/03/13 18:19:53 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:19:53 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for MSTest.TestAdapter.
  proxy | 2024/03/13 18:19:53 [284] GET https://api.nuget.org:443/v3-flatcontainer/mstest.testadapter/3.2.2/mstest.testadapter.nuspec
  proxy | 2024/03/13 18:19:53 [284] 200 https://api.nuget.org:443/v3-flatcontainer/mstest.testadapter/3.2.2/mstest.testadapter.nuspec
  ..
updater | 2024/03/13 18:19:54 INFO <job_799587273> Updating MSTest.TestAdapter from 3.1.1 to 3.2.2
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency MSTest.TestAdapter --new-version 3.2.2 --previous-version 3.1.1 --verbose
  proxy | 2024/03/13 18:19:56 [310] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/13 18:19:56 [311] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
updater | 2024/03/13 18:20:10 INFO <job_799587273> Checking if MSTest.TestFramework 3.1.1 needs updating
updater | 2024/03/13 18:20:10 INFO <job_799587273> Filtered out 32 pre-release versions
  proxy | 2024/03/13 18:20:10 [563] GET https://api.nuget.org:443/v3-flatcontainer/mstest.testframework/3.1.1/mstest.testframework.nuspec
  proxy | 2024/03/13 18:20:10 [563] 200 https://api.nuget.org:443/v3-flatcontainer/mstest.testframework/3.1.1/mstest.testframework.nuspec
  proxy | 2024/03/13 18:20:11 [565] GET https://api.nuget.org:443/v3-flatcontainer/mstest.testframework/3.2.2/mstest.testframework.nuspec
  proxy | 2024/03/13 18:20:11 [565] 200 https://api.nuget.org:443/v3-flatcontainer/mstest.testframework/3.2.2/mstest.testframework.nuspec
updater | 2024/03/13 18:20:11 INFO <job_799587273> Latest version is 3.2.2
updater | 2024/03/13 18:20:11 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:20:11 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for MSTest.TestFramework.
  proxy | 2024/03/13 18:20:11 [567] GET https://api.nuget.org:443/v3-flatcontainer/mstest.testframework/3.2.2/mstest.testframework.nuspec
  proxy | 2024/03/13 18:20:11 [567] 200 https://api.nuget.org:443/v3-flatcontainer/mstest.testframework/3.2.2/mstest.testframework.nuspec
updater | 2024/03/13 18:20:11 INFO <job_799587273> Updating MSTest.TestFramework from 3.1.1 to 3.2.2
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency MSTest.TestFramework --new-version 3.2.2 --previous-version 3.1.1 --verbose
  proxy | 2024/03/13 18:20:12 [570] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/13 18:20:12 [571] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
updater | 2024/03/13 18:20:23 INFO <job_799587273> Checking if Microsoft.NET.Test.Sdk 17.8.0 needs updating
updater | 2024/03/13 18:20:23 INFO <job_799587273> Filtered out 101 pre-release versions
  proxy | 2024/03/13 18:20:23 [615] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.net.test.sdk/17.8.0/microsoft.net.test.sdk.nuspec
  proxy | 2024/03/13 18:20:23 [615] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.net.test.sdk/17.8.0/microsoft.net.test.sdk.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETCoreApp3.1 .NETFramework4.6.2 --verbose
updater | The package is compatible.
  proxy | 2024/03/13 18:20:24 [617] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.net.test.sdk/17.9.0/microsoft.net.test.sdk.nuspec
  proxy | 2024/03/13 18:20:24 [617] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.net.test.sdk/17.9.0/microsoft.net.test.sdk.nuspec
updater | 2024/03/13 18:20:24 INFO <job_799587273> Latest version is 17.9.0
updater | 2024/03/13 18:20:24 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:20:24 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for Microsoft.NET.Test.Sdk.
  proxy | 2024/03/13 18:20:24 [619] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.net.test.sdk/17.9.0/microsoft.net.test.sdk.nuspec
  proxy | 2024/03/13 18:20:24 [619] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.net.test.sdk/17.9.0/microsoft.net.test.sdk.nuspec
  proxy | 2024/03/13 18:20:24 [621] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.testplatform.testhost/17.9.0/microsoft.testplatform.testhost.nuspec
  proxy | 2024/03/13 18:20:24 [621] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.testplatform.testhost/17.9.0/microsoft.testplatform.testhost.nuspec
  proxy | 2024/03/13 18:20:24 [623] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.testplatform.objectmodel/17.9.0/microsoft.testplatform.objectmodel.nuspec
  proxy | 2024/03/13 18:20:24 [623] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.testplatform.objectmodel/17.9.0/microsoft.testplatform.objectmodel.nuspec
  proxy | 2024/03/13 18:20:24 [625] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.codecoverage/17.9.0/microsoft.codecoverage.nuspec
  proxy | 2024/03/13 18:20:24 [625] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.codecoverage/17.9.0/microsoft.codecoverage.nuspec
updater | 2024/03/13 18:20:24 INFO <job_799587273> Updating Microsoft.NET.Test.Sdk from 17.8.0 to 17.9.0
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency Microsoft.NET.Test.Sdk --new-version 17.9.0 --previous-version 17.8.0 --verbose
  proxy | 2024/03/13 18:20:26 [628] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/13 18:20:26 [629] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
updater | 2024/03/13 18:20:37 INFO <job_799587273> Checking if Serilog 3.0.1 needs updating
updater | 2024/03/13 18:20:37 INFO <job_799587273> Filtered out 354 pre-release versions
  proxy | 2024/03/13 18:20:37 [681] GET https://api.nuget.org:443/v3-flatcontainer/serilog/3.0.1/serilog.nuspec
  proxy | 2024/03/13 18:20:37 [681] 200 https://api.nuget.org:443/v3-flatcontainer/serilog/3.0.1/serilog.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETFramework4.6.2 .NETFramework4.7.1 net5.0 net6.0 net7.0 .NETStandard2.0 .NETStandard2.1 --verbose
updater | The package is compatible.
  proxy | 2024/03/13 18:20:38 [683] GET https://api.nuget.org:443/v3-flatcontainer/serilog/3.1.1/serilog.nuspec
  proxy | 2024/03/13 18:20:38 [683] 200 https://api.nuget.org:443/v3-flatcontainer/serilog/3.1.1/serilog.nuspec
updater | 2024/03/13 18:20:38 INFO <job_799587273> Latest version is 3.1.1
updater | 2024/03/13 18:20:38 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:20:38 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for Serilog.
  proxy | 2024/03/13 18:20:38 [685] GET https://api.nuget.org:443/v3-flatcontainer/serilog/3.1.1/serilog.nuspec
  proxy | 2024/03/13 18:20:38 [685] 200 https://api.nuget.org:443/v3-flatcontainer/serilog/3.1.1/serilog.nuspec
  proxy | 2024/03/13 18:20:38 [687] GET https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.diagnosticsource/7.0.2/system.diagnostics.diagnosticsource.nuspec
  proxy | 2024/03/13 18:20:38 [687] 200 https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.diagnosticsource/7.0.2/system.diagnostics.diagnosticsource.nuspec
updater | 2024/03/13 18:20:38 INFO <job_799587273> Updating Serilog from 3.0.1 to 3.1.1
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency Serilog --new-version 3.1.1 --previous-version 3.0.1 --verbose
  proxy | 2024/03/13 18:20:40 [690] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/13 18:20:40 [691] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
updater | 2024/03/13 18:20:51 INFO <job_799587273> Checking if Serilog.AspNetCore 7.0.0 needs updating
updater | 2024/03/13 18:20:51 INFO <job_799587273> Filtered out 86 pre-release versions
  proxy | 2024/03/13 18:20:51 [737] GET https://api.nuget.org:443/v3-flatcontainer/serilog.aspnetcore/7.0.0/serilog.aspnetcore.nuspec
  proxy | 2024/03/13 18:20:51 [737] 200 https://api.nuget.org:443/v3-flatcontainer/serilog.aspnetcore/7.0.0/serilog.aspnetcore.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETFramework4.6.2 net6.0 net7.0 .NETStandard2.0 .NETStandard2.1 --verbose
updater | The package is compatible.
  proxy | 2024/03/13 18:20:52 [739] GET https://api.nuget.org:443/v3-flatcontainer/serilog.aspnetcore/8.0.1/serilog.aspnetcore.nuspec
  proxy | 2024/03/13 18:20:52 [739] 200 https://api.nuget.org:443/v3-flatcontainer/serilog.aspnetcore/8.0.1/serilog.aspnetcore.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETFramework4.6.2 net6.0 net7.0 net8.0 .NETStandard2.0 --verbose
updater | The package is compatible.
updater | 2024/03/13 18:20:53 INFO <job_799587273> Latest version is 8.0.1
updater | 2024/03/13 18:20:53 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:20:53 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for Serilog.AspNetCore.
  proxy | 2024/03/13 18:20:53 [741] GET https://api.nuget.org:443/v3-flatcontainer/serilog.aspnetcore/8.0.1/serilog.aspnetcore.nuspec
  proxy | 2024/03/13 18:20:53 [741] 200 https://api.nuget.org:443/v3-flatcontainer/serilog.aspnetcore/8.0.1/serilog.aspnetcore.nuspec
  ...
updater | 2024/03/13 18:20:54 INFO <job_799587273> Updating Serilog.AspNetCore, Serilog, Serilog.Sinks.Console
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency Serilog.AspNetCore --new-version 8.0.1 --previous-version 7.0.0 --verbose
  proxy | 2024/03/13 18:20:56 [786] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Found incorrect peer [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
  proxy | 2024/03/13 18:21:08 [875] GET https://api.nuget.org:443/v3-flatcontainer/serilog/3.1.0/serilog.nuspec
  proxy | 2024/03/13 18:21:08 [875] 200 https://api.nuget.org:443/v3-flatcontainer/serilog/3.1.0/serilog.nuspec
updater | 2024/03/13 18:21:08 INFO <job_799587273> Checking if Serilog.Sinks.Console 4.1.0 needs updating
updater | 2024/03/13 18:21:08 INFO <job_799587273> Filtered out 71 pre-release versions
  proxy | 2024/03/13 18:21:09 [877] GET https://api.nuget.org:443/v3-flatcontainer/serilog.sinks.console/4.1.0/serilog.sinks.console.nuspec
  proxy | 2024/03/13 18:21:09 [877] 200 https://api.nuget.org:443/v3-flatcontainer/serilog.sinks.console/4.1.0/serilog.sinks.console.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms .NETFramework4.5 .NETStandard1.3 net5.0 .NETStandard2.0 --verbose
updater | The package is compatible.
  proxy | 2024/03/13 18:21:09 [879] GET https://api.nuget.org:443/v3-flatcontainer/serilog.sinks.console/5.0.1/serilog.sinks.console.nuspec
  proxy | 2024/03/13 18:21:09 [879] 200 https://api.nuget.org:443/v3-flatcontainer/serilog.sinks.console/5.0.1/serilog.sinks.console.nuspec
updater | 2024/03/13 18:21:09 INFO <job_799587273> Latest version is 5.0.1
updater | 2024/03/13 18:21:09 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:21:09 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for Serilog.Sinks.Console.
  proxy | 2024/03/13 18:21:09 [881] GET https://api.nuget.org:443/v3-flatcontainer/serilog.sinks.console/5.0.1/serilog.sinks.console.nuspec
  proxy | 2024/03/13 18:21:09 [881] 200 https://api.nuget.org:443/v3-flatcontainer/serilog.sinks.console/5.0.1/serilog.sinks.console.nuspec
updater | 2024/03/13 18:21:09 INFO <job_799587273> Updating Serilog.Sinks.Console, Serilog
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency Serilog.Sinks.Console --new-version 5.0.1 --previous-version 4.1.0 --verbose
  proxy | 2024/03/13 18:21:11 [884] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/13 18:21:11 [885] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Root package [Serilog.Sinks.Console/4.1.0] was not updated; skipping dependencies.
updater | Update complete.
updater | 2024/03/13 18:21:23 ERROR <job_799587273> Error processing Serilog.Sinks.Console (Dependabot::DependabotError)
updater | 2024/03/13 18:21:23 ERROR <job_799587273> FileUpdater failed
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:114:in `create_change_for'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:72:in `block in compile_all_dependency_changes_for'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `each'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `compile_all_dependency_changes_for'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:70:in `dependency_change'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:127:in `run_update_for'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:109:in `block in run_grouped_dependency_updates'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:108:in `each'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:108:in `run_grouped_dependency_updates'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:55:in `perform'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/03/13 18:21:23 ERROR <job_799587273> bin/update_files.rb:33:in `<main>'
updater | 2024/03/13 18:21:23 INFO <job_799587273> Checking if coverlet.collector 6.0.0 needs updating
  proxy | 2024/03/13 18:21:23 [939] GET https://api.nuget.org:443/v3-flatcontainer/coverlet.collector/6.0.0/coverlet.collector.nuspec
  proxy | 2024/03/13 18:21:23 [939] 200 https://api.nuget.org:443/v3-flatcontainer/coverlet.collector/6.0.0/coverlet.collector.nuspec
  proxy | 2024/03/13 18:21:23 [945] GET https://api.nuget.org:443/v3-flatcontainer/coverlet.collector/6.0.2/coverlet.collector.nuspec
  proxy | 2024/03/13 18:21:23 [945] 200 https://api.nuget.org:443/v3-flatcontainer/coverlet.collector/6.0.2/coverlet.collector.nuspec
updater | 2024/03/13 18:21:23 INFO <job_799587273> Latest version is 6.0.2
updater | 2024/03/13 18:21:23 INFO <job_799587273> Requirements to unlock all
updater | 2024/03/13 18:21:23 INFO <job_799587273> Requirements update strategy 
updater | Finding updated dependencies for coverlet.collector.
  proxy | 2024/03/13 18:21:23 [947] GET https://api.nuget.org:443/v3-flatcontainer/coverlet.collector/6.0.2/coverlet.collector.nuspec
  proxy | 2024/03/13 18:21:23 [947] 200 https://api.nuget.org:443/v3-flatcontainer/coverlet.collector/6.0.2/coverlet.collector.nuspec
updater | 2024/03/13 18:21:23 INFO <job_799587273> Updating coverlet.collector from 6.0.0 to 6.0.2
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj --dependency coverlet.collector --new-version 6.0.2 --previous-version 6.0.0 --verbose
  proxy | 2024/03/13 18:21:25 [950] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2024/03/13 18:21:25 [951] POST https://dc.services.visualstudio.com:443/v2/track
  ...
updater |   No dotnet-tools.json files found.
updater | Running for project file [Dependabot.hack.csproj]
updater | Updating project [/home/dependabot/dependabot-updater/repo/Dependabot.hack.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
updater | 2024/03/13 18:21:37 INFO <job_799587273> Creating a pull request for 'nuget-dependencies'
  proxy | 2024/03/13 18:21:37 [999] GET https://api.github.com:443/repos/willbush/dependabot-cpm-updates/commits?per_page=100
  proxy | 2024/03/13 18:21:37 [999] * authenticating github api request with token for api.github.com
  ...
updater | 2024/03/13 18:21:56 INFO <job_799587273> Finished job processing
updater | 2024/03/13 18:21:56 INFO Results:
updater | +------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | MSTest.TestAdapter ( from 3.1.1 to 3.2.2 ), MSTest.TestFramework ( from 3.1.1 to 3.2.2 ), Microsoft.NET.Test.Sdk ( fr... |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------------------+
updater | |     Dependencies failed to update     |
updater | +-----------------------+---------------+
updater | | Serilog.Sinks.Console | unknown_error |
updater | +-----------------------+---------------+
updater | time="2024-03-13T18:21:56Z" level=info msg="task complete" container_id=job-799587273-updater exit_code=0 job_id=799587273 step=updater
```

**Comment by willbush** [comment]
Oh wait! it did make a PR though https://github.com/willbush/dependabot-cpm-updates/pull/1

**Comment by willbush** [comment]
Now to make a GH action to merge from the props file into csproj file..

**Comment by willbush** [comment]
I made a [script](https://github.com/willbush/dependabot-cpm-updates/blob/main/Dependabot.hack.regenerate.sh) and [GH action](https://github.com/willbush/dependabot-cpm-updates/blob/main/Dependabot.hack.regenerate.sh) that makes a [PR](https://github.com/willbush/dependabot-cpm-updates/pull/2) to update the root level `csproj` file.

I believe this will be good enough for us. I can't speak to this issue, but https://github.com/dependabot/dependabot-core/issues/8872 can be closed.

**Comment by martincostello** [comment]
@brettfo Having added the sentinel project, the updates are now working again as expected 👍

**Comment by abdulapopoola** [comment]
Awesome news @martincostello ! Closing this out then. Thanks!!

**Comment by willbush** [comment]
@abdulapopoola shouldn't dependabot secrets expand as env vars in a `nuget.conig` or is it specified another way?

I'm getting:

`The variable '%TENASKA_PACKAGE_ACCESS_PAT%' could not be expanded in NuGet.Config`

All I could find is this: https://github.com/dependabot/dependabot-core/pull/8879

**Comment by abdulapopoola** [comment]
Tagging @brettfo
