### ISSUE TITLE
Dependabot does not update private packages

### ISSUE THREAD

**Issue by benjaminoerskov** [dependabot/dependabot-core#8881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### dependabot.yml content

```
version: 2
registries:
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Affinity-IT/index.json/
    token: ${{secrets.NUGET_FEED_WRITE}}
  public:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    # Check private registry
    registries:
      - "nuget-github"
      - "public"
    # Check the registry for updates every day
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 5
``` 

### Updated dependency

affinityit.core

### What you expected to see, versus what you actually saw

Expected:
Dependabot to update my private package

Actually:
Got 200 ok response:
```
  proxy | 2024/01/24 09:37:09 [012] 200 https://nuget.pkg.github.com:443/Affinity-IT/affinityit.core/index.json
``` 
Dependency is hereafter not processed and nothing happens.

I can see in the logs that it authenticates ok and can find the package. I have about 20 new patch versions on this package.
We have recently switched from storing our credentials as a PAT in the nuget.config file, to storing it as a secret in github. Before the switch this worked just fine, now im seeing this error.

### Images of the diff or a link to the PR, issue, or logs

proxy | 2024/01/24 09:36:47 proxy starting, commit: 07d59135734a484cdcd1b34f737c7bca281bcf94
  proxy | 2024/01/24 09:36:47 * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/24 09:36:47 * authenticating nuget feed request (host: api.nuget.org, bearer auth)
  proxy | 2024/01/24 09:36:47 Listening (:1080)
updater | 2024-01-24T09:36:49.499834988 [778171328:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-01-24T09:36:52Z" level=info msg="guest starting" commit=5265bc7c42825390c331713cef4ed23c69721bbb
updater | time="2024-01-24T09:36:52Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=778171328 updater_timeout=45m0s updater_version=361c994a0de63657c9ff97f6358c13ccf382232d-nuget
updater | 2024/01/24 09:36:56 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/24 09:37:01 INFO <job_778171328> Starting job processing
  proxy | 2024/01/24 09:37:01 [002] GET https://github.com:443/Affinity-IT/services-blob/info/refs?service=git-upload-pack
  proxy | 2024/01/24 09:37:01 [002] * authenticating git server request (host: github.com)
  proxy | 2024/01/24 09:37:02 [002] 200 https://github.com:443/Affinity-IT/services-blob/info/refs?service=git-upload-pack
  proxy | 2024/01/24 09:37:02 [004] POST https://github.com:443/Affinity-IT/services-blob/git-upload-pack
  proxy | 2024/01/24 09:37:02 [004] * authenticating git server request (host: github.com)
  proxy | 2024/01/24 09:37:02 [004] 200 https://github.com:443/Affinity-IT/services-blob/git-upload-pack
  proxy | 2024/01/24 09:37:02 [006] POST https://github.com:443/Affinity-IT/services-blob/git-upload-pack
  proxy | 2024/01/24 09:37:02 [006] * authenticating git server request (host: github.com)
  proxy | 2024/01/24 09:37:02 [006] 200 https://github.com:443/Affinity-IT/services-blob/git-upload-pack
updater | 2024/01/24 09:37:02 INFO <job_778171328> Finished job processing
updater | time="2024-01-24T09:37:02Z" level=info msg="task complete" container_id=job-778171328-file-fetcher exit_code=0 job_id=778171328 step=fetcher
updater | 2024/01/24 09:37:05 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/24 09:37:07 INFO <job_778171328> Starting job processing
updater | 2024/01/24 09:37:07 WARN <job_778171328> The variable '%Nuget_AffinityITUsername%' could not be expanded in NuGet.Config
updater | 
updater | 2024/01/24 09:37:07 WARN <job_778171328> The variable '%Nuget_AffinityITPassword%' could not be expanded in NuGet.Config
updater | 
  proxy | 2024/01/24 09:37:08 [008] GET https://nuget.pkg.github.com:443/Affinity-IT/index.json/
  proxy | 2024/01/24 09:37:08 [008] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/24 09:37:08 [008] 200 https://nuget.pkg.github.com:443/Affinity-IT/index.json/
  proxy | 2024/01/24 09:37:08 [010] GET https://nuget.pkg.github.com:443/Affinity-IT/index.json
  proxy | 2024/01/24 09:37:08 [010] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/24 09:37:08 [010] 200 https://nuget.pkg.github.com:443/Affinity-IT/index.json
  proxy | 2024/01/24 09:37:08 [012] GET https://nuget.pkg.github.com:443/Affinity-IT/affinityit.core/index.json
  proxy | 2024/01/24 09:37:08 [012] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/24 09:37:09 [012] 200 https://nuget.pkg.github.com:443/Affinity-IT/affinityit.core/index.json
  proxy | 2024/01/24 09:37:10 [014] GET https://api.nuget.org:443/v3/registration5-gz-semver2/affinityit.core/index.json
  proxy | 2024/01/24 09:37:10 [014] 404 https://api.nuget.org:443/v3/registration5-gz-semver2/affinityit.core/index.json
updater | 2024/01/24 09:37:10 WARN <job_778171328> The variable '%Nuget_AffinityITUsername%' could not be expanded in NuGet.Config
updater | 
updater | 2024/01/24 09:37:10 WARN <job_778171328> The variable '%Nuget_AffinityITPassword%' could not be expanded in NuGet.Config
updater | 
  proxy | 2024/01/24 09:37:10 [016] GET https://nuget.pkg.github.com:443/Affinity-IT/automapper/index.json
  proxy | 2024/01/24 09:37:10 [016] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/24 09:37:10 [016] 404 https://nuget.pkg.github.com:443/Affinity-IT/automapper/index.json
  proxy | 2024/01/24 09:37:10 [018] GET https://api.nuget.org:443/v3/registration5-gz-semver2/automapper/index.json
  proxy | 2024/01/24 09:37:10 [018] 200 https://api.nuget.org:443/v3/registration5-gz-semver2/automapper/index.json
  proxy | 2024/01/24 09:37:10 [020] GET https://api.nuget.org:443/v3/registration5-gz-semver2/automapper/page/1.1.0.118/3.1.0-ci1033.json

**Comment by benjaminoerskov** [comment]
If I run "@dependabot recreate" on an old PR I get the following:

Looks like AffinityIT.Core is no longer a dependency, so this is no longer needed.

**Comment by abdulapopoola** [comment]
is this resolved now @benjaminoerskov ?

**Comment by benjaminoerskov** [comment]
@abdulapopoola Its still not working for me. However I found out that there is a difference from triggering dependabot manually and when its triggered automaticly. Last night I got the following log instead:
```
updater | 2024/01/25 00:38:58 INFO <job_778493153> Checking if AffinityIT.Core 8.0.49-rc05-feature-newtonsoft needs updating
  proxy | 2024/01/25 00:38:58 [780] GET https://api.nuget.org:443/v3/registration5-gz-semver2/affinityit.core/index.json
  proxy | 2024/01/25 00:38:58 [780] 404 https://api.nuget.org:443/v3/registration5-gz-semver2/affinityit.core/index.json
  proxy | 2024/01/25 00:38:58 [782] GET https://api.nuget.org:443/v3-flatcontainer/affinityit.core/8.0.49-rc05-feature-newtonsoft/affinityit.core.nuspec
  proxy | 2024/01/25 00:38:58 [782] 404 https://api.nuget.org:443/v3-flatcontainer/affinityit.core/8.0.49-rc05-feature-newtonsoft/affinityit.core.nuspec
  proxy | 2024/01/25 00:38:58 [784] GET https://nuget.pkg.github.com:443/Affinity-IT/download/affinityit.core/8.0.49-rc05-feature-newtonsoft/affinityit.core.8.0.49-rc05-feature-newtonsoft.nupkg
  proxy | 2024/01/25 00:38:58 [784] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/25 00:38:59 [784] 302 https://nuget.pkg.github.com:443/Affinity-IT/download/affinityit.core/8.0.49-rc05-feature-newtonsoft/affinityit.core.8.0.49-rc05-feature-newtonsoft.nupkg
updater | 2024/01/25 00:38:59 INFO <job_778493153> Latest version is 8.0.53
updater | 2024/01/25 00:38:59 INFO <job_778493153> Requirements to unlock all
updater | 2024/01/25 00:38:59 INFO <job_778493153> Requirements update strategy 
updater | Finding updated dependencies for AffinityIT.Core.
  proxy | 2024/01/25 00:38:59 [786] GET https://api.nuget.org:443/v3-flatcontainer/affinityit.core/8.0.53/affinityit.core.nuspec
  proxy | 2024/01/25 00:38:59 [786] 404 https://api.nuget.org:443/v3-flatcontainer/affinityit.core/8.0.53/affinityit.core.nuspec
  proxy | 2024/01/25 00:38:59 [788] GET https://nuget.pkg.github.com:443/Affinity-IT/download/affinityit.core/8.0.53/affinityit.core.8.0.53.nupkg
  proxy | 2024/01/25 00:38:59 [788] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2024/01/25 00:38:59 [788] 302 https://nuget.pkg.github.com:443/Affinity-IT/download/affinityit.core/8.0.53/affinityit.core.8.0.53.nupkg
updater | 2024/01/25 00:38:59 INFO <job_778493153> Updating AffinityIT.Core from 8.0.49-rc05-feature-newtonsoft to 8.0.53
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Ajour.Services.Authentication/Ajour.Services.Authentication.csproj --dependency AffinityIT.Core --new-version 8.0.53 --previous-version 8.0.49-rc05-feature-newtonsoft  --verbose
``` 

Then for some reason I get an error anyway:

```
updater | 2024/01/25 00:39:27 ERROR <job_778493153> Error processing AffinityIT.Core (Dependabot::DependabotError)
updater | 2024/01/25 00:39:27 ERROR <job_778493153> FileUpdater failed
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:38:in `run'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/01/25 00:39:27 ERROR <job_778493153> bin/update_files.rb:24:in `<main>'
``` 

And then it recaps:

```
updater | 2024/01/25 00:39:29 INFO <job_778493153> Finished job processing
updater | 2024/01/25 00:39:29 INFO Results:
updater | Dependabot encountered '2' error(s) during execution, please check the logs for more details.
updater | +-----------------------------------------+
updater | |      Dependencies failed to update      |
updater | +-------------------------+---------------+
updater | | AffinityIT.Core         | unknown_error |
updater | +-------------------------+---------------+
updater | time="2024-01-25T00:39:29Z" level=info msg="task complete" container_id=job-778493153-updater exit_code=0 job_id=778493153 step=updater
```

**Comment by ivanmalich** [comment]
Hey, also got the same issue with Github Private registry yesterday based on Dependabot jobs run history ([related to this Github issue](https://github.com/dependabot/dependabot-core/issues/8759)). But today after manual re-run it seems like it works for me 😸

**Comment by benjaminoerskov** [comment]
In my case the problem was that I didnt have the `index.json` in the end if the url, even though the guide ([here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#nuget-feed)) doesnt mention this.

Updated `dependabot.yml` file:
```
version: 2
registries:
  nuget-github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Affinity-IT/index.json
    token: ${{secrets.NUGET_FEED_WRITE}}
    
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    # Check private registry
    registries: '*'
    # Check the registry for updates every day
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 5
```

**Comment by abdulapopoola** [comment]
Great find @benjaminoerskov ; I can take a note to ensure that our guidelines are updated. Closing this out.

**Comment by abdulapopoola** [comment]
Thanks for spotting the issue @benjaminoerskov ; [our docs have also been updated. ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?hello=world#nuget-feed)
